load("lib.j")
runtests("core")
runtests("numbers")
runtests("strings")
runtests("corelib")
runtests("hashing")
runtests("arrayops")
# runtests("sparse") # TODO: FIXME!
runtests("lapack")
runtests("fft")
runtests("arpack")
runtests("random")
