# core tests
runtests("core")
runtests("numbers")
runtests("strings")
runtests("unicode")
runtests("corelib")
runtests("hashing")
runtests("remote")

# array/matrix tests
runtests("arrayops")
runtests("lapack")
runtests("factorizations")
runtests("fft")
runtests("sparse")
runtests("arpack")
runtests("bitarray")

# other tests
runtests("random")
runtests("special")
runtests("functional")
runtests("bigint")
runtests("distributions")
runtests("combinatorics")
runtests("statistics")
runtests("integers")
runtests("glpk")
runtests("linprog")
runtests("sparse")
runtests("bigfloat")
runtests("poly")
runtests("file")
runtests("Rmath")
