runtests("glpk")
runtests("linprog")
runtests("bigfloat")
runtests("poly")
runtests("file")
runtests("Rmath")
runtests("zlib")
runtests("options")
runtests("image")
runtests("iterators")

runtests("perf")
