@profile sleep(0.1)
let iobuf = IOBuffer()
    Profile.print(iobuf)
    str = takebuf_string(iobuf)
    @test !isempty(str)
    Profile.print(iobuf, format=:flat)
    str = takebuf_string(iobuf)
    @test !isempty(str)
    Profile.print(iobuf, format=:tree, C=true)
    str = takebuf_string(iobuf)
    @test !isempty(str)
    Profile.clear()
    @test isempty(Profile.fetch())
end
