# This file is a part of Julia. License is MIT: http://julialang.org/license

include("strings/basic.jl")
include("strings/isvalid.jl")
include("strings/search.jl")
#include("strings/cmp.jl")
include("strings/SubStrings.jl")
#include("strings/hash.jl")
#include("strings/pad.jl")
include("strings/replace.jl")
include("strings/join.jl")
#include("strings/chop.jl")
include("strings/map.jl")
include("strings/escape.jl")
#include("strings/split.jl")
include("strings/RevStrings.jl")
include("strings/strip.jl")
include("strings/parse.jl")
include("strings/hex.jl")
include("strings/cstring.jl")
include("strings/io.jl")
