;;; julia-mode.el --- Major mode for editing Julia source code

;; Copyright (C) 2009-2014 Julia contributors
;; URL: https://github.com/JuliaLang/julia
;; Version: 0.3
;; Keywords: languages

;;; Usage:
;; Put the following code in your .emacs, site-load.el, or other relevant file
;; (add-to-list 'load-path "path-to-julia-mode")
;; (require 'julia-mode)

;;; Commentary:
;; This is the official Emacs mode for editing Julia programs.

;;; License:
;; Permission is hereby granted, free of charge, to any person obtaining
;; a copy of this software and associated documentation files (the
;; "Software"), to deal in the Software without restriction, including
;; without limitation the rights to use, copy, modify, merge, publish,
;; distribute, sublicense, and/or sell copies of the Software, and to
;; permit persons to whom the Software is furnished to do so, subject to
;; the following conditions:
;; 
;; The above copyright notice and this permission notice shall be
;; included in all copies or substantial portions of the Software.
;; 
;; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
;; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
;; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
;; NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
;; LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
;; OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
;; WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

;;; Code:

(defvar julia-mode-hook nil)

(defvar julia-basic-offset)

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-mode))

;; define ignore-errors macro if it isn't present
;; (necessary for emacs 22 compatibility)
(when (not (fboundp 'ignore-errors))
  (defmacro ignore-errors (body) `(condition-case nil ,body (error nil))))

(defvar julia-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?_ "w" table)   ; underscores in words
    (modify-syntax-entry ?@ "w" table)
    (modify-syntax-entry ?. "_" table)
    (modify-syntax-entry ?# "< 14" table)  ; # single-line and multiline start
    (modify-syntax-entry ?= ". 23bn" table)
    (modify-syntax-entry ?\n ">" table)  ; \n single-line comment end
    (modify-syntax-entry ?\{ "(} " table)
    (modify-syntax-entry ?\} "){ " table)
    (modify-syntax-entry ?\[ "(] " table)
    (modify-syntax-entry ?\] ")[ " table)
    (modify-syntax-entry ?\( "() " table)
    (modify-syntax-entry ?\) ")( " table)
    ;(modify-syntax-entry ?\\ "." table)  ; \ is an operator outside quotes
    (modify-syntax-entry ?'  "." table)  ; character quote or transpose
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?` "\"" table)
    ;; (modify-syntax-entry ?\" "." table)
    (modify-syntax-entry ?? "." table)
    (modify-syntax-entry ?$ "." table)
    (modify-syntax-entry ?& "." table)
    (modify-syntax-entry ?* "." table)
    (modify-syntax-entry ?+ "." table)
    (modify-syntax-entry ?- "." table)
    (modify-syntax-entry ?< "." table)
    (modify-syntax-entry ?> "." table)
    (modify-syntax-entry ?% "." table)
    table)
  "Syntax table for `julia-mode'.")

;; syntax table that holds within strings
(defvar julia-mode-string-syntax-table
  (let ((table (make-syntax-table)))
    table)
  "Syntax table for `julia-mode'.")

;; disable " inside char quote
(defvar julia-mode-char-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?\" "." table)
    table)
  "Syntax table for `julia-mode'.")

(defconst julia-string-regex
  "\"[^\"]*?\\(\\(\\\\\\\\\\)*\\\\\"[^\"]*?\\)*\"")

(defconst julia-char-regex
  "\\(\\s(\\|\\s-\\|-\\|[,%=<>\\+*/?&|$!\\^~\\\\;:]\\|^\\)\\('\\(\\([^']*?[^\\\\]\\)\\|\\(\\\\\\\\\\)\\)'\\)")

(defconst julia-unquote-regex
  "\\(\\s(\\|\\s-\\|-\\|[,%=<>\\+*/?&|!\\^~\\\\;:]\\|^\\)\\($[a-zA-Z0-9_]+\\)")

(defconst julia-forloop-in-regex
  "for +.*[^
].* \\(in\\)\\(\\s-\\|$\\)+")

(defconst julia-function-regex
  (rx symbol-start "function" (1+ space) (group (1+ (or word ?_ ?!)))))

(defconst julia-type-regex
  (rx symbol-start "type" (1+ space) (group (1+ (or word ?_)))))

(defconst julia-macro-regex
  "@\\w+")

(defconst julia-keyword-regex
  (regexp-opt
   '("if" "else" "elseif" "while" "for" "begin" "end" "quote"
     "try" "catch" "return" "local" "abstract" "function" "macro" "ccall"
     "finally" "typealias" "break" "continue" "type" "global"
     "module" "using" "import" "export" "const" "let" "bitstype" "do"
     "baremodule" "importall" "immutable")))

(defconst julia-font-lock-keywords
  (list
   '("\\<\\(\\|Uint\\(8\\|16\\|32\\|64\\|128\\)\\|Int\\(8\\|16\\|32\\|64\\|128\\)\\|BigInt\\|Integer\\|BigFloat\\|FloatingPoint\\|Float16\\|Float32\\|Float64\\|Complex128\\|Complex64\\|ComplexPair\\|Bool\\|Char\\|DataType\\|Number\\|Real\\|Int\\|Uint\\|Array\\|DArray\\|AbstractArray\\|AbstractVector\\|AbstractMatrix\\|AbstractSparseMatrix\\|SubArray\\|StridedArray\\|StridedVector\\|StridedMatrix\\|VecOrMat\\|StridedVecOrMat\\|DenseArray\\|Range\\|OrdinalRange\\|StepRange\\|UnitRange\\|FloatRange\\|SparseMatrixCSC\\|Tuple\\|NTuple\\|Symbol\\|Function\\|Vector\\|Matrix\\|Union\\|Type\\|Any\\|Complex\\|None\\|String\\|Ptr\\|Void\\|Exception\\|Task\\|Signed\\|Unsigned\\|Associative\\|Dict\\|IO\\|IOStream\\|Rational\\|Regex\\|RegexMatch\\|Set\\|IntSet\\|ASCIIString\\|UTF8String\\|ByteString\\|Expr\\|WeakRef\\|Nothing\\|ObjectIdDict\\|SubString\\)\\>" .
     font-lock-type-face)
    (cons julia-keyword-regex 'font-lock-keyword-face)
    (cons julia-macro-regex 'font-lock-keyword-face)
    (cons
     (regexp-opt
      '("true" "false" "C_NULL" "Inf" "NaN" "Inf32" "NaN32" "nothing"))
     'font-lock-constant-face)
    (list julia-unquote-regex 2 'font-lock-constant-face)
    (list julia-char-regex 2 'font-lock-string-face)
    (list julia-forloop-in-regex 1 'font-lock-keyword-face)
    (list julia-function-regex 1 'font-lock-function-name-face)
    (list julia-type-regex 1 'font-lock-type-face)
))

(defconst julia-block-start-keywords
  (list "if" "while" "for" "begin" "try" "function" "type" "let" "macro"
	"quote" "do" "immutable"))

(defconst julia-block-end-keywords
  (list "end" "else" "elseif" "catch" "finally"))

(defun julia-member (item lst)
  (if (null lst)
      nil
    (or (equal item (car lst))
	(julia-member item (cdr lst)))))

(if (not (fboundp 'evenp))
    (defun evenp (x) (zerop (% x 2))))

(defun julia-find-comment-open (p0)
  (if (< (point) p0)
      nil
    (if (and (equal (char-after (point)) ?#)
	     (evenp (julia-strcount
		     (buffer-substring p0 (point)) ?\")))
	t
      (if (= (point) p0)
	  nil
	(progn (backward-char 1)
	       (julia-find-comment-open p0))))))

(defun julia-in-comment ()
  (save-excursion
    (julia-find-comment-open (line-beginning-position))))

(defun julia-strcount (str chr)
  (let ((i 0)
	(c 0))
    (while (< i (length str))
      (if (equal (elt str i) chr)
	  (setq c (+ c 1)))
      (setq i (+ i 1)))
    c))

(defun julia-in-brackets ()
  (let ((before (buffer-substring (line-beginning-position) (point))))
    (> (julia-strcount before ?[)
       (julia-strcount before ?]))))

(defun julia-at-keyword (kw-list)
  "Return the word at point if it matches any keyword in KW-LIST.
KW-LIST is a list of strings.  The word at point is not considered
a keyword if used as a field name, X.word, or quoted, :word."
  (and (or (= (point) 1)
	   (and (not (equal (char-before (point)) ?.))
		(not (equal (char-before (point)) ?:))))
       (not (julia-in-comment))
       (not (julia-in-brackets))
       (julia-member (current-word t) kw-list)))

;; if backward-sexp gives an error, move back 1 char to move over the '('
(defun julia-safe-backward-sexp ()
  (if (condition-case nil (backward-sexp) (error t))
      (ignore-errors (backward-char))))

(defun julia-last-open-block-pos (min)
  "Move back and return the position of the last open block, if one found.
Do not move back beyond position MIN."
  (let ((count 0))
    (while (not (or (> count 0) (<= (point) min)))
      (julia-safe-backward-sexp)
      (setq count
	    (cond ((julia-at-keyword julia-block-start-keywords)
		   (+ count 1))
		  ((and (equal (current-word t) "end")
			(not (julia-in-comment)) (not (julia-in-brackets)))
		   (- count 1))
		  (t count))))
    (if (> count 0)
	(point)
      nil)))

(defun julia-last-open-block (min)
  "Move back and return indentation level for last open block.
Do not move back beyond MIN."
  (let ((pos (julia-last-open-block-pos min)))
    (and pos
	 (progn
	   (goto-char pos)
	   (+ julia-basic-offset (current-indentation))))))

(defun julia-paren-indent ()
  "Return indent by last opening paren."
  (let* ((p (parse-partial-sexp
             (save-excursion
               ;; only indent by paren if the last open
               ;; paren is closer than the last open
               ;; block
               (or (julia-last-open-block-pos (point-min))
                   (point-min)))
             (progn (beginning-of-line)
                    (point))))
         (pos (cadr p)))
    (if (or (= 0 (car p)) (null pos))
        nil
      (progn (goto-char pos) (+ 1 (current-column))))))

(defun julia-indent-line ()
  "Indent current line of julia code."
  (interactive)
  (let* ((point-offset (- (current-column) (current-indentation))))
    (end-of-line)
    (indent-line-to
     (or (save-excursion (ignore-errors (julia-paren-indent)))
         (save-excursion
           (let ((endtok (progn
                           (beginning-of-line)
                           (forward-to-indentation 0)
                           (julia-at-keyword julia-block-end-keywords))))
             (ignore-errors (+ (julia-last-open-block (point-min))
                               (if endtok (- julia-basic-offset) 0)))))
         ;; previous line ends in =
         (save-excursion
           (if (and (not (equal (point-min) (line-beginning-position)))
                    (progn
                      (forward-line -1)
                      (end-of-line) (backward-char 1)
                      (equal (char-after (point)) ?=)))
               (+ julia-basic-offset (current-indentation))
             nil))
         ;; take same indentation as previous line
         (save-excursion (forward-line -1)
                         (current-indentation))
         0))
    ;; Point is now at the beginning of indentation, restore it
    ;; to its original position (relative to indentation).
    (when (>= point-offset 0)
      (move-to-column (+ (current-indentation) point-offset)))))

(defalias 'julia-mode-prog-mode
  (if (fboundp 'prog-mode)
      'prog-mode
    'fundamental-mode))

;;; IMENU
(defvar julia-imenu-generic-expression
  ;; don't use syntax classes, screws egrep
  '(("Function (_)" "[ \t]*function[ \t]+\\(_[^ \t\n]*\\)" 1)
    ("Function" "^[ \t]*function[ \t]+\\([^_][^\t\n]*\\)" 1)
    ("Const" "[ \t]*const \\([^ \t\n]*\\)" 1)
    ("Type"  "^[ \t]*[a-zA-Z0-9_]*type[a-zA-Z0-9_]* \\([^ \t\n]*\\)" 1)
    ("Require"      " *\\(\\brequire\\)(\\([^ \t\n)]*\\)" 2)
    ("Include"      " *\\(\\binclude\\)(\\([^ \t\n)]*\\)" 2)
    ;; ("Classes" "^.*setClass(\\(.*\\)," 1)
    ;; ("Coercions" "^.*setAs(\\([^,]+,[^,]*\\)," 1) ; show from and to
    ;; ("Generics" "^.*setGeneric(\\([^,]*\\)," 1)
    ;; ("Methods" "^.*set\\(Group\\|Replace\\)?Method(\"\\(.+\\)\"," 2)
    ;; ;;[ ]*\\(signature=\\)?(\\(.*,?\\)*\\)," 1)
    ;; ;;
    ;; ;;("Other" "^\\(.+\\)\\s-*<-[ \t\n]*[^\\(function\\|read\\|.*data\.frame\\)]" 1)
    ;; ("Package" "^.*\\(library\\|require\\)(\\(.*\\)," 2)
    ;; ("Data" "^\\(.+\\)\\s-*<-[ \t\n]*\\(read\\|.*data\.frame\\).*(" 1)))
    ))

;;;###autoload
(define-derived-mode julia-mode julia-mode-prog-mode "Julia"
  "Major mode for editing julia code."
  (set-syntax-table julia-mode-syntax-table)
  (set (make-local-variable 'comment-start) "# ")
  (set (make-local-variable 'comment-start-skip) "#+\\s-*")
  (set (make-local-variable 'font-lock-defaults) '(julia-font-lock-keywords))
  (set (make-local-variable 'font-lock-syntactic-keywords)
       (list
	(list "\\(\\\\\\)\\s-*\".*?\"" 1 julia-mode-char-syntax-table)))
  (set (make-local-variable 'font-lock-syntactic-keywords)
        (list
 	(list julia-char-regex 2
 	      julia-mode-char-syntax-table)
        (list julia-string-regex 0
              julia-mode-string-syntax-table)
	))
  (set (make-local-variable 'indent-line-function) 'julia-indent-line)
  (set (make-local-variable 'julia-basic-offset) 4)
  (setq indent-tabs-mode nil)
  (setq imenu-generic-expression julia-imenu-generic-expression)
  (imenu-add-to-menubar "Imenu"))

(defvar julia-latexsubs (make-hash-table :test 'equal))

(defun julia-latexsub (arg)
  "Perform a LaTeX-like Unicode symbol substitution."
  (interactive "*i")
  (let ((orig-pt (point)))
    (while (not (or (bobp) (= ?\\ (char-before))
		    (= ?\s (char-syntax (char-before)))))
      (backward-char))
    (if (and (not (bobp)) (= ?\\ (char-before)))
        (progn
          (backward-char)
          (let ((sub (gethash (buffer-substring (point) orig-pt) julia-latexsubs)))
            (if sub
                (progn
                  (delete-region (point) orig-pt)
                  (insert sub))
              (goto-char orig-pt))))
      (goto-char orig-pt))))

(defalias 'latexsub 'julia-latexsub)

(defun julia-latexsub-or-indent (arg)
  "Either indent according to mode or perform a LaTeX-like symbol substution"
  (interactive "*i")
  (if (latexsub arg)
      (indent-according-to-mode)))
(define-key julia-mode-map (kbd "TAB") 'julia-latexsub-or-indent)

(defalias 'latexsub-or-indent 'julia-latexsub-or-indent)

; LaTeX-like symbol substitutions, equivalent to those in the Julia REPL,
; generated by:
; for (k,v) in sort!(collect(Base.REPLCompletions.latex_symbols), by=x->x[2])
;    println("(puthash \"$(escape_string(k))\" \"$(escape_string(v))\" julia-latexsubs)")
; end
(puthash "\\textexclamdown" "¡" julia-latexsubs)
(puthash "\\sterling" "£" julia-latexsubs)
(puthash "\\yen" "¥" julia-latexsubs)
(puthash "\\textbrokenbar" "¦" julia-latexsubs)
(puthash "\\S" "§" julia-latexsubs)
(puthash "\\textasciidieresis" "¨" julia-latexsubs)
(puthash "\\copyright" "©" julia-latexsubs)
(puthash "\\textordfeminine" "ª" julia-latexsubs)
(puthash "\\neg" "¬" julia-latexsubs)
(puthash "\\circledR" "®" julia-latexsubs)
(puthash "\\textasciimacron" "¯" julia-latexsubs)
(puthash "\\degree" "°" julia-latexsubs)
(puthash "\\pm" "±" julia-latexsubs)
(puthash "\\^2" "²" julia-latexsubs)
(puthash "\\^3" "³" julia-latexsubs)
(puthash "\\textasciiacute" "´" julia-latexsubs)
(puthash "\\P" "¶" julia-latexsubs)
(puthash "\\cdotp" "·" julia-latexsubs)
(puthash "\\^1" "¹" julia-latexsubs)
(puthash "\\textordmasculine" "º" julia-latexsubs)
(puthash "\\textonequarter" "¼" julia-latexsubs)
(puthash "\\textonehalf" "½" julia-latexsubs)
(puthash "\\textthreequarters" "¾" julia-latexsubs)
(puthash "\\textquestiondown" "¿" julia-latexsubs)
(puthash "\\AA" "Å" julia-latexsubs)
(puthash "\\AE" "Æ" julia-latexsubs)
(puthash "\\DH" "Ð" julia-latexsubs)
(puthash "\\times" "×" julia-latexsubs)
(puthash "\\O" "Ø" julia-latexsubs)
(puthash "\\TH" "Þ" julia-latexsubs)
(puthash "\\ss" "ß" julia-latexsubs)
(puthash "\\aa" "å" julia-latexsubs)
(puthash "\\ae" "æ" julia-latexsubs)
(puthash "\\eth" "ð" julia-latexsubs)
(puthash "\\div" "÷" julia-latexsubs)
(puthash "\\o" "ø" julia-latexsubs)
(puthash "\\th" "þ" julia-latexsubs)
(puthash "\\DJ" "Đ" julia-latexsubs)
(puthash "\\dj" "đ" julia-latexsubs)
(puthash "\\Elzxh" "ħ" julia-latexsubs)
(puthash "\\hbar" "ħ" julia-latexsubs)
(puthash "\\imath" "ı" julia-latexsubs)
(puthash "\\L" "Ł" julia-latexsubs)
(puthash "\\l" "ł" julia-latexsubs)
(puthash "\\NG" "Ŋ" julia-latexsubs)
(puthash "\\ng" "ŋ" julia-latexsubs)
(puthash "\\OE" "Œ" julia-latexsubs)
(puthash "\\oe" "œ" julia-latexsubs)
(puthash "\\texthvlig" "ƕ" julia-latexsubs)
(puthash "\\textnrleg" "ƞ" julia-latexsubs)
(puthash "\\textdoublepipe" "ǂ" julia-latexsubs)
(puthash "\\Elztrna" "ɐ" julia-latexsubs)
(puthash "\\Elztrnsa" "ɒ" julia-latexsubs)
(puthash "\\Elzopeno" "ɔ" julia-latexsubs)
(puthash "\\Elzrtld" "ɖ" julia-latexsubs)
(puthash "\\Elzschwa" "ə" julia-latexsubs)
(puthash "\\varepsilon" "ɛ" julia-latexsubs)
(puthash "\\Elzpgamma" "ɣ" julia-latexsubs)
(puthash "\\Elzpbgam" "ɤ" julia-latexsubs)
(puthash "\\Elztrnh" "ɥ" julia-latexsubs)
(puthash "\\Elzbtdl" "ɬ" julia-latexsubs)
(puthash "\\Elzrtll" "ɭ" julia-latexsubs)
(puthash "\\Elztrnm" "ɯ" julia-latexsubs)
(puthash "\\Elztrnmlr" "ɰ" julia-latexsubs)
(puthash "\\Elzltlmr" "ɱ" julia-latexsubs)
(puthash "\\Elzltln" "ɲ" julia-latexsubs)
(puthash "\\Elzrtln" "ɳ" julia-latexsubs)
(puthash "\\Elzclomeg" "ɷ" julia-latexsubs)
(puthash "\\textphi" "ɸ" julia-latexsubs)
(puthash "\\Elztrnr" "ɹ" julia-latexsubs)
(puthash "\\Elztrnrl" "ɺ" julia-latexsubs)
(puthash "\\Elzrttrnr" "ɻ" julia-latexsubs)
(puthash "\\Elzrl" "ɼ" julia-latexsubs)
(puthash "\\Elzrtlr" "ɽ" julia-latexsubs)
(puthash "\\Elzfhr" "ɾ" julia-latexsubs)
(puthash "\\Elzrtls" "ʂ" julia-latexsubs)
(puthash "\\Elzesh" "ʃ" julia-latexsubs)
(puthash "\\Elztrnt" "ʇ" julia-latexsubs)
(puthash "\\Elzrtlt" "ʈ" julia-latexsubs)
(puthash "\\Elzpupsil" "ʊ" julia-latexsubs)
(puthash "\\Elzpscrv" "ʋ" julia-latexsubs)
(puthash "\\Elzinvv" "ʌ" julia-latexsubs)
(puthash "\\Elzinvw" "ʍ" julia-latexsubs)
(puthash "\\Elztrny" "ʎ" julia-latexsubs)
(puthash "\\Elzrtlz" "ʐ" julia-latexsubs)
(puthash "\\Elzyogh" "ʒ" julia-latexsubs)
(puthash "\\Elzglst" "ʔ" julia-latexsubs)
(puthash "\\Elzreglst" "ʕ" julia-latexsubs)
(puthash "\\Elzinglst" "ʖ" julia-latexsubs)
(puthash "\\textturnk" "ʞ" julia-latexsubs)
(puthash "\\Elzdyogh" "ʤ" julia-latexsubs)
(puthash "\\Elztesh" "ʧ" julia-latexsubs)
(puthash "\\^h" "ʰ" julia-latexsubs)
(puthash "\\^j" "ʲ" julia-latexsubs)
(puthash "\\^r" "ʳ" julia-latexsubs)
(puthash "\\^w" "ʷ" julia-latexsubs)
(puthash "\\^y" "ʸ" julia-latexsubs)
(puthash "\\rasp" "ʼ" julia-latexsubs)
(puthash "\\textasciicaron" "ˇ" julia-latexsubs)
(puthash "\\Elzverts" "ˈ" julia-latexsubs)
(puthash "\\Elzverti" "ˌ" julia-latexsubs)
(puthash "\\Elzlmrk" "ː" julia-latexsubs)
(puthash "\\Elzhlmrk" "ˑ" julia-latexsubs)
(puthash "\\Elzsbrhr" "˒" julia-latexsubs)
(puthash "\\Elzsblhr" "˓" julia-latexsubs)
(puthash "\\Elzrais" "˔" julia-latexsubs)
(puthash "\\Elzlow" "˕" julia-latexsubs)
(puthash "\\u" "˘" julia-latexsubs)
(puthash "\\texttildelow" "˜" julia-latexsubs)
(puthash "\\^l" "ˡ" julia-latexsubs)
(puthash "\\^s" "ˢ" julia-latexsubs)
(puthash "\\^x" "ˣ" julia-latexsubs)
(puthash "\\grave" "̀" julia-latexsubs)
(puthash "\\acute" "́" julia-latexsubs)
(puthash "\\hat" "̂" julia-latexsubs)
(puthash "\\tilde" "̃" julia-latexsubs)
(puthash "\\bar" "̄" julia-latexsubs)
(puthash "\\breve" "̆" julia-latexsubs)
(puthash "\\dot" "̇" julia-latexsubs)
(puthash "\\ddot" "̈" julia-latexsubs)
(puthash "\\ocirc" "̊" julia-latexsubs)
(puthash "\\H" "̋" julia-latexsubs)
(puthash "\\check" "̌" julia-latexsubs)
(puthash "\\Elzpalh" "̡" julia-latexsubs)
(puthash "\\Elzrh" "̢" julia-latexsubs)
(puthash "\\c" "̧" julia-latexsubs)
(puthash "\\k" "̨" julia-latexsubs)
(puthash "\\Elzsbbrg" "̪" julia-latexsubs)
(puthash "\\Elzxl" "̵" julia-latexsubs)
(puthash "\\Elzbar" "̶" julia-latexsubs)
(puthash "\\sout" "̶" julia-latexsubs)
(puthash "\\Alpha" "Α" julia-latexsubs)
(puthash "\\Beta" "Β" julia-latexsubs)
(puthash "\\Gamma" "Γ" julia-latexsubs)
(puthash "\\Delta" "Δ" julia-latexsubs)
(puthash "\\Epsilon" "Ε" julia-latexsubs)
(puthash "\\Zeta" "Ζ" julia-latexsubs)
(puthash "\\Eta" "Η" julia-latexsubs)
(puthash "\\Theta" "Θ" julia-latexsubs)
(puthash "\\Iota" "Ι" julia-latexsubs)
(puthash "\\Kappa" "Κ" julia-latexsubs)
(puthash "\\Lambda" "Λ" julia-latexsubs)
(puthash "\\Xi" "Ξ" julia-latexsubs)
(puthash "\\Pi" "Π" julia-latexsubs)
(puthash "\\Rho" "Ρ" julia-latexsubs)
(puthash "\\Sigma" "Σ" julia-latexsubs)
(puthash "\\Tau" "Τ" julia-latexsubs)
(puthash "\\Upsilon" "Υ" julia-latexsubs)
(puthash "\\Phi" "Φ" julia-latexsubs)
(puthash "\\Chi" "Χ" julia-latexsubs)
(puthash "\\Psi" "Ψ" julia-latexsubs)
(puthash "\\Omega" "Ω" julia-latexsubs)
(puthash "\\alpha" "α" julia-latexsubs)
(puthash "\\beta" "β" julia-latexsubs)
(puthash "\\gamma" "γ" julia-latexsubs)
(puthash "\\delta" "δ" julia-latexsubs)
(puthash "\\zeta" "ζ" julia-latexsubs)
(puthash "\\eta" "η" julia-latexsubs)
(puthash "\\theta" "θ" julia-latexsubs)
(puthash "\\iota" "ι" julia-latexsubs)
(puthash "\\kappa" "κ" julia-latexsubs)
(puthash "\\lambda" "λ" julia-latexsubs)
(puthash "\\mu" "μ" julia-latexsubs)
(puthash "\\nu" "ν" julia-latexsubs)
(puthash "\\xi" "ξ" julia-latexsubs)
(puthash "\\pi" "π" julia-latexsubs)
(puthash "\\rho" "ρ" julia-latexsubs)
(puthash "\\varsigma" "ς" julia-latexsubs)
(puthash "\\sigma" "σ" julia-latexsubs)
(puthash "\\tau" "τ" julia-latexsubs)
(puthash "\\upsilon" "υ" julia-latexsubs)
(puthash "\\varphi" "φ" julia-latexsubs)
(puthash "\\chi" "χ" julia-latexsubs)
(puthash "\\psi" "ψ" julia-latexsubs)
(puthash "\\omega" "ω" julia-latexsubs)
(puthash "\\vartheta" "ϑ" julia-latexsubs)
(puthash "\\phi" "ϕ" julia-latexsubs)
(puthash "\\varpi" "ϖ" julia-latexsubs)
(puthash "\\Stigma" "Ϛ" julia-latexsubs)
(puthash "\\Digamma" "Ϝ" julia-latexsubs)
(puthash "\\digamma" "ϝ" julia-latexsubs)
(puthash "\\Koppa" "Ϟ" julia-latexsubs)
(puthash "\\Sampi" "Ϡ" julia-latexsubs)
(puthash "\\varkappa" "ϰ" julia-latexsubs)
(puthash "\\varrho" "ϱ" julia-latexsubs)
(puthash "\\textTheta" "ϴ" julia-latexsubs)
(puthash "\\epsilon" "ϵ" julia-latexsubs)
(puthash "\\backepsilon" "϶" julia-latexsubs)
(puthash "\\^A" "\u1d2c" julia-latexsubs)
(puthash "\\^B" "\u1d2e" julia-latexsubs)
(puthash "\\^D" "\u1d30" julia-latexsubs)
(puthash "\\^E" "\u1d31" julia-latexsubs)
(puthash "\\^G" "\u1d33" julia-latexsubs)
(puthash "\\^H" "\u1d34" julia-latexsubs)
(puthash "\\^I" "\u1d35" julia-latexsubs)
(puthash "\\^J" "\u1d36" julia-latexsubs)
(puthash "\\^K" "\u1d37" julia-latexsubs)
(puthash "\\^L" "\u1d38" julia-latexsubs)
(puthash "\\^M" "\u1d39" julia-latexsubs)
(puthash "\\^N" "\u1d3a" julia-latexsubs)
(puthash "\\^O" "\u1d3c" julia-latexsubs)
(puthash "\\^P" "\u1d3e" julia-latexsubs)
(puthash "\\^R" "\u1d3f" julia-latexsubs)
(puthash "\\^T" "\u1d40" julia-latexsubs)
(puthash "\\^U" "\u1d41" julia-latexsubs)
(puthash "\\^W" "\u1d42" julia-latexsubs)
(puthash "\\^a" "\u1d43" julia-latexsubs)
(puthash "\\^alpha" "\u1d45" julia-latexsubs)
(puthash "\\^b" "\u1d47" julia-latexsubs)
(puthash "\\^d" "\u1d48" julia-latexsubs)
(puthash "\\^e" "\u1d49" julia-latexsubs)
(puthash "\\^epsilon" "\u1d4b" julia-latexsubs)
(puthash "\\^g" "\u1d4d" julia-latexsubs)
(puthash "\\^k" "\u1d4f" julia-latexsubs)
(puthash "\\^m" "\u1d50" julia-latexsubs)
(puthash "\\^o" "\u1d52" julia-latexsubs)
(puthash "\\^p" "\u1d56" julia-latexsubs)
(puthash "\\^t" "\u1d57" julia-latexsubs)
(puthash "\\^u" "\u1d58" julia-latexsubs)
(puthash "\\^v" "\u1d5b" julia-latexsubs)
(puthash "\\^beta" "\u1d5d" julia-latexsubs)
(puthash "\\^gamma" "\u1d5e" julia-latexsubs)
(puthash "\\^delta" "\u1d5f" julia-latexsubs)
(puthash "\\^phi" "\u1d60" julia-latexsubs)
(puthash "\\^chi" "\u1d61" julia-latexsubs)
(puthash "\\_i" "\u1d62" julia-latexsubs)
(puthash "\\_r" "\u1d63" julia-latexsubs)
(puthash "\\_u" "\u1d64" julia-latexsubs)
(puthash "\\_v" "\u1d65" julia-latexsubs)
(puthash "\\_beta" "\u1d66" julia-latexsubs)
(puthash "\\_gamma" "\u1d67" julia-latexsubs)
(puthash "\\_rho" "\u1d68" julia-latexsubs)
(puthash "\\_phi" "\u1d69" julia-latexsubs)
(puthash "\\_chi" "\u1d6a" julia-latexsubs)
(puthash "\\^c" "\u1d9c" julia-latexsubs)
(puthash "\\^f" "\u1da0" julia-latexsubs)
(puthash "\\^iota" "\u1da5" julia-latexsubs)
(puthash "\\^Phi" "\u1db2" julia-latexsubs)
(puthash "\\^z" "\u1dbb" julia-latexsubs)
(puthash "\\^theta" "\u1dbf" julia-latexsubs)
(puthash "\\enspace" " " julia-latexsubs)
(puthash "\\quad" " " julia-latexsubs)
(puthash "\\thickspace" " " julia-latexsubs)
(puthash "\\thinspace" " " julia-latexsubs)
(puthash "\\hspace" " " julia-latexsubs)
(puthash "\\endash" "–" julia-latexsubs)
(puthash "\\emdash" "—" julia-latexsubs)
(puthash "\\Vert" "‖" julia-latexsubs)
(puthash "\\lq" "‘" julia-latexsubs)
(puthash "\\rq" "’" julia-latexsubs)
(puthash "\\Elzreapos" "‛" julia-latexsubs)
(puthash "\\textquotedblleft" "“" julia-latexsubs)
(puthash "\\textquotedblright" "”" julia-latexsubs)
(puthash "\\dagger" "†" julia-latexsubs)
(puthash "\\ddagger" "‡" julia-latexsubs)
(puthash "\\bullet" "•" julia-latexsubs)
(puthash "\\dots" "…" julia-latexsubs)
(puthash "\\textperthousand" "‰" julia-latexsubs)
(puthash "\\textpertenthousand" "‱" julia-latexsubs)
(puthash "\\prime" "′" julia-latexsubs)
(puthash "\\backprime" "‵" julia-latexsubs)
(puthash "\\guilsinglleft" "‹" julia-latexsubs)
(puthash "\\guilsinglright" "›" julia-latexsubs)
(puthash "\\nolinebreak" "\u2060" julia-latexsubs)
(puthash "\\^0" "⁰" julia-latexsubs)
(puthash "\\^i" "ⁱ" julia-latexsubs)
(puthash "\\^4" "⁴" julia-latexsubs)
(puthash "\\^5" "⁵" julia-latexsubs)
(puthash "\\^6" "⁶" julia-latexsubs)
(puthash "\\^7" "⁷" julia-latexsubs)
(puthash "\\^8" "⁸" julia-latexsubs)
(puthash "\\^9" "⁹" julia-latexsubs)
(puthash "\\^+" "⁺" julia-latexsubs)
(puthash "\\^-" "⁻" julia-latexsubs)
(puthash "\\^=" "⁼" julia-latexsubs)
(puthash "\\^(" "⁽" julia-latexsubs)
(puthash "\\^)" "⁾" julia-latexsubs)
(puthash "\\^n" "ⁿ" julia-latexsubs)
(puthash "\\_0" "₀" julia-latexsubs)
(puthash "\\_1" "₁" julia-latexsubs)
(puthash "\\_2" "₂" julia-latexsubs)
(puthash "\\_3" "₃" julia-latexsubs)
(puthash "\\_4" "₄" julia-latexsubs)
(puthash "\\_5" "₅" julia-latexsubs)
(puthash "\\_6" "₆" julia-latexsubs)
(puthash "\\_7" "₇" julia-latexsubs)
(puthash "\\_8" "₈" julia-latexsubs)
(puthash "\\_9" "₉" julia-latexsubs)
(puthash "\\_+" "₊" julia-latexsubs)
(puthash "\\_-" "₋" julia-latexsubs)
(puthash "\\_=" "₌" julia-latexsubs)
(puthash "\\_(" "₍" julia-latexsubs)
(puthash "\\_)" "₎" julia-latexsubs)
(puthash "\\_a" "\u2090" julia-latexsubs)
(puthash "\\_e" "\u2091" julia-latexsubs)
(puthash "\\_o" "\u2092" julia-latexsubs)
(puthash "\\_x" "\u2093" julia-latexsubs)
(puthash "\\_schwa" "\u2094" julia-latexsubs)
(puthash "\\_h" "\u2095" julia-latexsubs)
(puthash "\\_k" "\u2096" julia-latexsubs)
(puthash "\\_l" "\u2097" julia-latexsubs)
(puthash "\\_m" "\u2098" julia-latexsubs)
(puthash "\\_n" "\u2099" julia-latexsubs)
(puthash "\\_p" "\u209a" julia-latexsubs)
(puthash "\\_s" "\u209b" julia-latexsubs)
(puthash "\\_t" "\u209c" julia-latexsubs)
(puthash "\\Elzpes" "₧" julia-latexsubs)
(puthash "\\euro" "€" julia-latexsubs)
(puthash "\\dddot" "⃛" julia-latexsubs)
(puthash "\\ddddot" "⃜" julia-latexsubs)
(puthash "\\hslash" "ℏ" julia-latexsubs)
(puthash "\\Im" "ℑ" julia-latexsubs)
(puthash "\\ell" "ℓ" julia-latexsubs)
(puthash "\\textnumero" "№" julia-latexsubs)
(puthash "\\wp" "℘" julia-latexsubs)
(puthash "\\Re" "ℜ" julia-latexsubs)
(puthash "\\Elzxrat" "℞" julia-latexsubs)
(puthash "\\texttrademark" "™" julia-latexsubs)
(puthash "\\mho" "℧" julia-latexsubs)
(puthash "\\aleph" "ℵ" julia-latexsubs)
(puthash "\\beth" "ℶ" julia-latexsubs)
(puthash "\\gimel" "ℷ" julia-latexsubs)
(puthash "\\daleth" "ℸ" julia-latexsubs)
(puthash "\\BbbPi" "ℿ" julia-latexsubs)
(puthash "\\bbsum" "⅀" julia-latexsubs)
(puthash "\\Game" "⅁" julia-latexsubs)
(puthash "\\leftarrow" "←" julia-latexsubs)
(puthash "\\uparrow" "↑" julia-latexsubs)
(puthash "\\rightarrow" "→" julia-latexsubs)
(puthash "\\downarrow" "↓" julia-latexsubs)
(puthash "\\leftrightarrow" "↔" julia-latexsubs)
(puthash "\\updownarrow" "↕" julia-latexsubs)
(puthash "\\nwarrow" "↖" julia-latexsubs)
(puthash "\\nearrow" "↗" julia-latexsubs)
(puthash "\\searrow" "↘" julia-latexsubs)
(puthash "\\swarrow" "↙" julia-latexsubs)
(puthash "\\nleftarrow" "↚" julia-latexsubs)
(puthash "\\nrightarrow" "↛" julia-latexsubs)
(puthash "\\leftsquigarrow" "↜" julia-latexsubs)
(puthash "\\rightsquigarrow" "↝" julia-latexsubs)
(puthash "\\twoheadleftarrow" "↞" julia-latexsubs)
(puthash "\\twoheadrightarrow" "↠" julia-latexsubs)
(puthash "\\leftarrowtail" "↢" julia-latexsubs)
(puthash "\\rightarrowtail" "↣" julia-latexsubs)
(puthash "\\mapsto" "↦" julia-latexsubs)
(puthash "\\hookleftarrow" "↩" julia-latexsubs)
(puthash "\\hookrightarrow" "↪" julia-latexsubs)
(puthash "\\looparrowleft" "↫" julia-latexsubs)
(puthash "\\looparrowright" "↬" julia-latexsubs)
(puthash "\\leftrightsquigarrow" "↭" julia-latexsubs)
(puthash "\\nleftrightarrow" "↮" julia-latexsubs)
(puthash "\\Lsh" "↰" julia-latexsubs)
(puthash "\\Rsh" "↱" julia-latexsubs)
(puthash "\\curvearrowleft" "↶" julia-latexsubs)
(puthash "\\curvearrowright" "↷" julia-latexsubs)
(puthash "\\circlearrowleft" "↺" julia-latexsubs)
(puthash "\\circlearrowright" "↻" julia-latexsubs)
(puthash "\\leftharpoonup" "↼" julia-latexsubs)
(puthash "\\leftharpoondown" "↽" julia-latexsubs)
(puthash "\\upharpoonleft" "↾" julia-latexsubs)
(puthash "\\upharpoonright" "↿" julia-latexsubs)
(puthash "\\rightharpoonup" "⇀" julia-latexsubs)
(puthash "\\rightharpoondown" "⇁" julia-latexsubs)
(puthash "\\downharpoonright" "⇂" julia-latexsubs)
(puthash "\\downharpoonleft" "⇃" julia-latexsubs)
(puthash "\\rightleftarrows" "⇄" julia-latexsubs)
(puthash "\\dblarrowupdown" "⇅" julia-latexsubs)
(puthash "\\leftrightarrows" "⇆" julia-latexsubs)
(puthash "\\leftleftarrows" "⇇" julia-latexsubs)
(puthash "\\upuparrows" "⇈" julia-latexsubs)
(puthash "\\rightrightarrows" "⇉" julia-latexsubs)
(puthash "\\downdownarrows" "⇊" julia-latexsubs)
(puthash "\\leftrightharpoons" "⇋" julia-latexsubs)
(puthash "\\rightleftharpoons" "⇌" julia-latexsubs)
(puthash "\\nLeftarrow" "⇍" julia-latexsubs)
(puthash "\\nRightarrow" "⇏" julia-latexsubs)
(puthash "\\Leftarrow" "⇐" julia-latexsubs)
(puthash "\\Uparrow" "⇑" julia-latexsubs)
(puthash "\\Rightarrow" "⇒" julia-latexsubs)
(puthash "\\Downarrow" "⇓" julia-latexsubs)
(puthash "\\Leftrightarrow" "⇔" julia-latexsubs)
(puthash "\\Updownarrow" "⇕" julia-latexsubs)
(puthash "\\Lleftarrow" "⇚" julia-latexsubs)
(puthash "\\Rrightarrow" "⇛" julia-latexsubs)
(puthash "\\DownArrowUpArrow" "⇵" julia-latexsubs)
(puthash "\\leftarrowtriangle" "⇽" julia-latexsubs)
(puthash "\\rightarrowtriangle" "⇾" julia-latexsubs)
(puthash "\\forall" "∀" julia-latexsubs)
(puthash "\\complement" "∁" julia-latexsubs)
(puthash "\\partial" "∂" julia-latexsubs)
(puthash "\\exists" "∃" julia-latexsubs)
(puthash "\\nexists" "∄" julia-latexsubs)
(puthash "\\varnothing" "∅" julia-latexsubs)
(puthash "\\del" "∇" julia-latexsubs)
(puthash "\\nabla" "∇" julia-latexsubs)
(puthash "\\in" "∈" julia-latexsubs)
(puthash "\\notin" "∉" julia-latexsubs)
(puthash "\\ni" "∋" julia-latexsubs)
(puthash "\\prod" "∏" julia-latexsubs)
(puthash "\\coprod" "∐" julia-latexsubs)
(puthash "\\sum" "∑" julia-latexsubs)
(puthash "\\minus" "−" julia-latexsubs)
(puthash "\\mp" "∓" julia-latexsubs)
(puthash "\\dotplus" "∔" julia-latexsubs)
(puthash "\\setminus" "∖" julia-latexsubs)
(puthash "\\ast" "∗" julia-latexsubs)
(puthash "\\circ" "∘" julia-latexsubs)
(puthash "\\surd" "√" julia-latexsubs)
(puthash "\\sqrt" "√" julia-latexsubs)
(puthash "\\cbrt" "∛" julia-latexsubs)
(puthash "\\propto" "∝" julia-latexsubs)
(puthash "\\infty" "∞" julia-latexsubs)
(puthash "\\rightangle" "∟" julia-latexsubs)
(puthash "\\angle" "∠" julia-latexsubs)
(puthash "\\measuredangle" "∡" julia-latexsubs)
(puthash "\\sphericalangle" "∢" julia-latexsubs)
(puthash "\\mid" "∣" julia-latexsubs)
(puthash "\\nmid" "∤" julia-latexsubs)
(puthash "\\parallel" "∥" julia-latexsubs)
(puthash "\\nparallel" "∦" julia-latexsubs)
(puthash "\\wedge" "∧" julia-latexsubs)
(puthash "\\vee" "∨" julia-latexsubs)
(puthash "\\cap" "∩" julia-latexsubs)
(puthash "\\cup" "∪" julia-latexsubs)
(puthash "\\int" "∫" julia-latexsubs)
(puthash "\\iint" "∬" julia-latexsubs)
(puthash "\\iiint" "∭" julia-latexsubs)
(puthash "\\oint" "∮" julia-latexsubs)
(puthash "\\oiint" "∯" julia-latexsubs)
(puthash "\\oiiint" "∰" julia-latexsubs)
(puthash "\\clwintegral" "∱" julia-latexsubs)
(puthash "\\therefore" "∴" julia-latexsubs)
(puthash "\\because" "∵" julia-latexsubs)
(puthash "\\Colon" "∷" julia-latexsubs)
(puthash "\\dotminus" "∸" julia-latexsubs)
(puthash "\\kernelcontraction" "∻" julia-latexsubs)
(puthash "\\sim" "∼" julia-latexsubs)
(puthash "\\backsim" "∽" julia-latexsubs)
(puthash "\\lazysinv" "∾" julia-latexsubs)
(puthash "\\wr" "≀" julia-latexsubs)
(puthash "\\nsim" "≁" julia-latexsubs)
(puthash "\\eqsim" "≂" julia-latexsubs)
(puthash "\\neqsim" "≂̸" julia-latexsubs)
(puthash "\\simeq" "≃" julia-latexsubs)
(puthash "\\nsime" "≄" julia-latexsubs)
(puthash "\\cong" "≅" julia-latexsubs)
(puthash "\\approxnotequal" "≆" julia-latexsubs)
(puthash "\\ncong" "≇" julia-latexsubs)
(puthash "\\approx" "≈" julia-latexsubs)
(puthash "\\napprox" "≉" julia-latexsubs)
(puthash "\\approxeq" "≊" julia-latexsubs)
(puthash "\\tildetrpl" "≋" julia-latexsubs)
(puthash "\\allequal" "≌" julia-latexsubs)
(puthash "\\asymp" "≍" julia-latexsubs)
(puthash "\\Bumpeq" "≎" julia-latexsubs)
(puthash "\\nBumpeq" "≎̸" julia-latexsubs)
(puthash "\\bumpeq" "≏" julia-latexsubs)
(puthash "\\nbumpeq" "≏̸" julia-latexsubs)
(puthash "\\doteq" "≐" julia-latexsubs)
(puthash "\\Doteq" "≑" julia-latexsubs)
(puthash "\\fallingdotseq" "≒" julia-latexsubs)
(puthash "\\risingdotseq" "≓" julia-latexsubs)
(puthash "\\coloneq" "≔" julia-latexsubs)
(puthash "\\eqcolon" "≕" julia-latexsubs)
(puthash "\\eqcirc" "≖" julia-latexsubs)
(puthash "\\circeq" "≗" julia-latexsubs)
(puthash "\\wedgeq" "≙" julia-latexsubs)
(puthash "\\starequal" "≛" julia-latexsubs)
(puthash "\\triangleq" "≜" julia-latexsubs)
(puthash "\\questeq" "≟" julia-latexsubs)
(puthash "\\ne" "≠" julia-latexsubs)
(puthash "\\equiv" "≡" julia-latexsubs)
(puthash "\\nequiv" "≢" julia-latexsubs)
(puthash "\\le" "≤" julia-latexsubs)
(puthash "\\ge" "≥" julia-latexsubs)
(puthash "\\leqq" "≦" julia-latexsubs)
(puthash "\\geqq" "≧" julia-latexsubs)
(puthash "\\lneqq" "≨" julia-latexsubs)
(puthash "\\lvertneqq" "≨︀" julia-latexsubs)
(puthash "\\gneqq" "≩" julia-latexsubs)
(puthash "\\gvertneqq" "≩︀" julia-latexsubs)
(puthash "\\ll" "≪" julia-latexsubs)
(puthash "\\NotLessLess" "≪̸" julia-latexsubs)
(puthash "\\gg" "≫" julia-latexsubs)
(puthash "\\NotGreaterGreater" "≫̸" julia-latexsubs)
(puthash "\\between" "≬" julia-latexsubs)
(puthash "\\nless" "≮" julia-latexsubs)
(puthash "\\ngtr" "≯" julia-latexsubs)
(puthash "\\nleq" "≰" julia-latexsubs)
(puthash "\\ngeq" "≱" julia-latexsubs)
(puthash "\\lesssim" "≲" julia-latexsubs)
(puthash "\\gtrsim" "≳" julia-latexsubs)
(puthash "\\lessgtr" "≶" julia-latexsubs)
(puthash "\\gtrless" "≷" julia-latexsubs)
(puthash "\\notlessgreater" "≸" julia-latexsubs)
(puthash "\\notgreaterless" "≹" julia-latexsubs)
(puthash "\\prec" "≺" julia-latexsubs)
(puthash "\\succ" "≻" julia-latexsubs)
(puthash "\\preccurlyeq" "≼" julia-latexsubs)
(puthash "\\succcurlyeq" "≽" julia-latexsubs)
(puthash "\\precsim" "≾" julia-latexsubs)
(puthash "\\nprecsim" "≾̸" julia-latexsubs)
(puthash "\\succsim" "≿" julia-latexsubs)
(puthash "\\nsuccsim" "≿̸" julia-latexsubs)
(puthash "\\nprec" "⊀" julia-latexsubs)
(puthash "\\nsucc" "⊁" julia-latexsubs)
(puthash "\\subset" "⊂" julia-latexsubs)
(puthash "\\supset" "⊃" julia-latexsubs)
(puthash "\\nsubset" "⊄" julia-latexsubs)
(puthash "\\nsupset" "⊅" julia-latexsubs)
(puthash "\\subseteq" "⊆" julia-latexsubs)
(puthash "\\supseteq" "⊇" julia-latexsubs)
(puthash "\\nsubseteq" "⊈" julia-latexsubs)
(puthash "\\nsupseteq" "⊉" julia-latexsubs)
(puthash "\\subsetneq" "⊊" julia-latexsubs)
(puthash "\\varsubsetneqq" "⊊︀" julia-latexsubs)
(puthash "\\supsetneq" "⊋" julia-latexsubs)
(puthash "\\varsupsetneq" "⊋︀" julia-latexsubs)
(puthash "\\cupdot" "⊍" julia-latexsubs)
(puthash "\\uplus" "⊎" julia-latexsubs)
(puthash "\\sqsubset" "⊏" julia-latexsubs)
(puthash "\\NotSquareSubset" "⊏̸" julia-latexsubs)
(puthash "\\sqsupset" "⊐" julia-latexsubs)
(puthash "\\NotSquareSuperset" "⊐̸" julia-latexsubs)
(puthash "\\sqsubseteq" "⊑" julia-latexsubs)
(puthash "\\sqsupseteq" "⊒" julia-latexsubs)
(puthash "\\sqcap" "⊓" julia-latexsubs)
(puthash "\\sqcup" "⊔" julia-latexsubs)
(puthash "\\oplus" "⊕" julia-latexsubs)
(puthash "\\ominus" "⊖" julia-latexsubs)
(puthash "\\otimes" "⊗" julia-latexsubs)
(puthash "\\oslash" "⊘" julia-latexsubs)
(puthash "\\odot" "⊙" julia-latexsubs)
(puthash "\\circledcirc" "⊚" julia-latexsubs)
(puthash "\\circledast" "⊛" julia-latexsubs)
(puthash "\\circleddash" "⊝" julia-latexsubs)
(puthash "\\boxplus" "⊞" julia-latexsubs)
(puthash "\\boxminus" "⊟" julia-latexsubs)
(puthash "\\boxtimes" "⊠" julia-latexsubs)
(puthash "\\boxdot" "⊡" julia-latexsubs)
(puthash "\\vdash" "⊢" julia-latexsubs)
(puthash "\\dashv" "⊣" julia-latexsubs)
(puthash "\\top" "⊤" julia-latexsubs)
(puthash "\\perp" "⊥" julia-latexsubs)
(puthash "\\models" "⊧" julia-latexsubs)
(puthash "\\vDash" "⊨" julia-latexsubs)
(puthash "\\Vdash" "⊩" julia-latexsubs)
(puthash "\\Vvdash" "⊪" julia-latexsubs)
(puthash "\\VDash" "⊫" julia-latexsubs)
(puthash "\\nvdash" "⊬" julia-latexsubs)
(puthash "\\nvDash" "⊭" julia-latexsubs)
(puthash "\\nVdash" "⊮" julia-latexsubs)
(puthash "\\nVDash" "⊯" julia-latexsubs)
(puthash "\\vartriangleleft" "⊲" julia-latexsubs)
(puthash "\\vartriangleright" "⊳" julia-latexsubs)
(puthash "\\trianglelefteq" "⊴" julia-latexsubs)
(puthash "\\trianglerighteq" "⊵" julia-latexsubs)
(puthash "\\original" "⊶" julia-latexsubs)
(puthash "\\image" "⊷" julia-latexsubs)
(puthash "\\multimap" "⊸" julia-latexsubs)
(puthash "\\hermitconjmatrix" "⊹" julia-latexsubs)
(puthash "\\intercal" "⊺" julia-latexsubs)
(puthash "\\veebar" "⊻" julia-latexsubs)
(puthash "\\rightanglearc" "⊾" julia-latexsubs)
(puthash "\\bigwedge" "⋀" julia-latexsubs)
(puthash "\\bigvee" "⋁" julia-latexsubs)
(puthash "\\bigcap" "⋂" julia-latexsubs)
(puthash "\\bigcup" "⋃" julia-latexsubs)
(puthash "\\diamond" "⋄" julia-latexsubs)
(puthash "\\cdot" "⋅" julia-latexsubs)
(puthash "\\star" "⋆" julia-latexsubs)
(puthash "\\divideontimes" "⋇" julia-latexsubs)
(puthash "\\bowtie" "⋈" julia-latexsubs)
(puthash "\\ltimes" "⋉" julia-latexsubs)
(puthash "\\rtimes" "⋊" julia-latexsubs)
(puthash "\\leftthreetimes" "⋋" julia-latexsubs)
(puthash "\\rightthreetimes" "⋌" julia-latexsubs)
(puthash "\\backsimeq" "⋍" julia-latexsubs)
(puthash "\\curlyvee" "⋎" julia-latexsubs)
(puthash "\\curlywedge" "⋏" julia-latexsubs)
(puthash "\\Subset" "⋐" julia-latexsubs)
(puthash "\\Supset" "⋑" julia-latexsubs)
(puthash "\\Cap" "⋒" julia-latexsubs)
(puthash "\\Cup" "⋓" julia-latexsubs)
(puthash "\\pitchfork" "⋔" julia-latexsubs)
(puthash "\\lessdot" "⋖" julia-latexsubs)
(puthash "\\gtrdot" "⋗" julia-latexsubs)
(puthash "\\verymuchless" "⋘" julia-latexsubs)
(puthash "\\ggg" "⋙" julia-latexsubs)
(puthash "\\lesseqgtr" "⋚" julia-latexsubs)
(puthash "\\gtreqless" "⋛" julia-latexsubs)
(puthash "\\curlyeqprec" "⋞" julia-latexsubs)
(puthash "\\curlyeqsucc" "⋟" julia-latexsubs)
(puthash "\\Elzsqspne" "⋥" julia-latexsubs)
(puthash "\\lnsim" "⋦" julia-latexsubs)
(puthash "\\gnsim" "⋧" julia-latexsubs)
(puthash "\\precnsim" "⋨" julia-latexsubs)
(puthash "\\succnsim" "⋩" julia-latexsubs)
(puthash "\\ntriangleleft" "⋪" julia-latexsubs)
(puthash "\\ntriangleright" "⋫" julia-latexsubs)
(puthash "\\ntrianglelefteq" "⋬" julia-latexsubs)
(puthash "\\ntrianglerighteq" "⋭" julia-latexsubs)
(puthash "\\vdots" "⋮" julia-latexsubs)
(puthash "\\cdots" "⋯" julia-latexsubs)
(puthash "\\adots" "⋰" julia-latexsubs)
(puthash "\\ddots" "⋱" julia-latexsubs)
(puthash "\\barwedge" "⌅" julia-latexsubs)
(puthash "\\lceil" "⌈" julia-latexsubs)
(puthash "\\rceil" "⌉" julia-latexsubs)
(puthash "\\lfloor" "⌊" julia-latexsubs)
(puthash "\\rfloor" "⌋" julia-latexsubs)
(puthash "\\recorder" "⌕" julia-latexsubs)
(puthash "\\ulcorner" "⌜" julia-latexsubs)
(puthash "\\urcorner" "⌝" julia-latexsubs)
(puthash "\\llcorner" "⌞" julia-latexsubs)
(puthash "\\lrcorner" "⌟" julia-latexsubs)
(puthash "\\frown" "⌢" julia-latexsubs)
(puthash "\\smile" "⌣" julia-latexsubs)
(puthash "\\obar" "⌽" julia-latexsubs)
(puthash "\\Elzdlcorn" "⎣" julia-latexsubs)
(puthash "\\lmoustache" "⎰" julia-latexsubs)
(puthash "\\rmoustache" "⎱" julia-latexsubs)
(puthash "\\textvisiblespace" "␣" julia-latexsubs)
(puthash "\\circledS" "Ⓢ" julia-latexsubs)
(puthash "\\Elzdshfnc" "┆" julia-latexsubs)
(puthash "\\Elzsqfnw" "┙" julia-latexsubs)
(puthash "\\diagup" "╱" julia-latexsubs)
(puthash "\\diagdown" "╲" julia-latexsubs)
(puthash "\\blacksquare" "■" julia-latexsubs)
(puthash "\\square" "□" julia-latexsubs)
(puthash "\\Elzvrecto" "▯" julia-latexsubs)
(puthash "\\bigtriangleup" "△" julia-latexsubs)
(puthash "\\blacktriangle" "▴" julia-latexsubs)
(puthash "\\vartriangle" "▵" julia-latexsubs)
(puthash "\\blacktriangleright" "▸" julia-latexsubs)
(puthash "\\triangleright" "▹" julia-latexsubs)
(puthash "\\bigtriangledown" "▽" julia-latexsubs)
(puthash "\\blacktriangledown" "▾" julia-latexsubs)
(puthash "\\triangledown" "▿" julia-latexsubs)
(puthash "\\blacktriangleleft" "◂" julia-latexsubs)
(puthash "\\triangleleft" "◃" julia-latexsubs)
(puthash "\\lozenge" "◊" julia-latexsubs)
(puthash "\\bigcirc" "○" julia-latexsubs)
(puthash "\\Elzcirfl" "◐" julia-latexsubs)
(puthash "\\Elzcirfr" "◑" julia-latexsubs)
(puthash "\\Elzcirfb" "◒" julia-latexsubs)
(puthash "\\Elzrvbull" "◘" julia-latexsubs)
(puthash "\\Elzsqfl" "◧" julia-latexsubs)
(puthash "\\Elzsqfr" "◨" julia-latexsubs)
(puthash "\\Elzsqfse" "◪" julia-latexsubs)
(puthash "\\bigstar" "★" julia-latexsubs)
(puthash "\\rightmoon" "☾" julia-latexsubs)
(puthash "\\mercury" "☿" julia-latexsubs)
(puthash "\\venus" "♀" julia-latexsubs)
(puthash "\\female" "♀" julia-latexsubs)
(puthash "\\male" "♂" julia-latexsubs)
(puthash "\\mars" "♂" julia-latexsubs)
(puthash "\\jupiter" "♃" julia-latexsubs)
(puthash "\\saturn" "♄" julia-latexsubs)
(puthash "\\uranus" "♅" julia-latexsubs)
(puthash "\\neptune" "♆" julia-latexsubs)
(puthash "\\pluto" "♇" julia-latexsubs)
(puthash "\\aries" "♈" julia-latexsubs)
(puthash "\\taurus" "♉" julia-latexsubs)
(puthash "\\gemini" "♊" julia-latexsubs)
(puthash "\\cancer" "♋" julia-latexsubs)
(puthash "\\leo" "♌" julia-latexsubs)
(puthash "\\virgo" "♍" julia-latexsubs)
(puthash "\\libra" "♎" julia-latexsubs)
(puthash "\\scorpio" "♏" julia-latexsubs)
(puthash "\\sagittarius" "♐" julia-latexsubs)
(puthash "\\capricornus" "♑" julia-latexsubs)
(puthash "\\aquarius" "♒" julia-latexsubs)
(puthash "\\pisces" "♓" julia-latexsubs)
(puthash "\\spadesuit" "♠" julia-latexsubs)
(puthash "\\heartsuit" "♡" julia-latexsubs)
(puthash "\\diamondsuit" "♢" julia-latexsubs)
(puthash "\\clubsuit" "♣" julia-latexsubs)
(puthash "\\quarternote" "♩" julia-latexsubs)
(puthash "\\eighthnote" "♪" julia-latexsubs)
(puthash "\\flat" "♭" julia-latexsubs)
(puthash "\\natural" "♮" julia-latexsubs)
(puthash "\\sharp" "♯" julia-latexsubs)
(puthash "\\checkmark" "✓" julia-latexsubs)
(puthash "\\maltese" "✠" julia-latexsubs)
(puthash "\\langle" "⟨" julia-latexsubs)
(puthash "\\rangle" "⟩" julia-latexsubs)
(puthash "\\longleftarrow" "⟵" julia-latexsubs)
(puthash "\\longrightarrow" "⟶" julia-latexsubs)
(puthash "\\longleftrightarrow" "⟷" julia-latexsubs)
(puthash "\\Longleftarrow" "⟸" julia-latexsubs)
(puthash "\\Longrightarrow" "⟹" julia-latexsubs)
(puthash "\\Longleftrightarrow" "⟺" julia-latexsubs)
(puthash "\\longmapsto" "⟼" julia-latexsubs)
(puthash "\\Mapsfrom" "⤆" julia-latexsubs)
(puthash "\\Mapsto" "⤇" julia-latexsubs)
(puthash "\\Uuparrow" "⤊" julia-latexsubs)
(puthash "\\Ddownarrow" "⤋" julia-latexsubs)
(puthash "\\bkarow" "⤍" julia-latexsubs)
(puthash "\\dbkarow" "⤏" julia-latexsubs)
(puthash "\\drbkarrow" "⤐" julia-latexsubs)
(puthash "\\UpArrowBar" "⤒" julia-latexsubs)
(puthash "\\DownArrowBar" "⤓" julia-latexsubs)
(puthash "\\twoheadrightarrowtail" "⤖" julia-latexsubs)
(puthash "\\hksearow" "⤥" julia-latexsubs)
(puthash "\\hkswarow" "⤦" julia-latexsubs)
(puthash "\\tona" "⤧" julia-latexsubs)
(puthash "\\toea" "⤨" julia-latexsubs)
(puthash "\\tosa" "⤩" julia-latexsubs)
(puthash "\\towa" "⤪" julia-latexsubs)
(puthash "\\rdiagovfdiag" "⤫" julia-latexsubs)
(puthash "\\fdiagovrdiag" "⤬" julia-latexsubs)
(puthash "\\seovnearrow" "⤭" julia-latexsubs)
(puthash "\\neovsearrow" "⤮" julia-latexsubs)
(puthash "\\fdiagovnearrow" "⤯" julia-latexsubs)
(puthash "\\rdiagovsearrow" "⤰" julia-latexsubs)
(puthash "\\neovnwarrow" "⤱" julia-latexsubs)
(puthash "\\nwovnearrow" "⤲" julia-latexsubs)
(puthash "\\ElzRlarr" "⥂" julia-latexsubs)
(puthash "\\ElzrLarr" "⥄" julia-latexsubs)
(puthash "\\Elzrarrx" "⥇" julia-latexsubs)
(puthash "\\LeftRightVector" "⥎" julia-latexsubs)
(puthash "\\RightUpDownVector" "⥏" julia-latexsubs)
(puthash "\\DownLeftRightVector" "⥐" julia-latexsubs)
(puthash "\\LeftUpDownVector" "⥑" julia-latexsubs)
(puthash "\\LeftVectorBar" "⥒" julia-latexsubs)
(puthash "\\RightVectorBar" "⥓" julia-latexsubs)
(puthash "\\RightUpVectorBar" "⥔" julia-latexsubs)
(puthash "\\RightDownVectorBar" "⥕" julia-latexsubs)
(puthash "\\DownLeftVectorBar" "⥖" julia-latexsubs)
(puthash "\\DownRightVectorBar" "⥗" julia-latexsubs)
(puthash "\\LeftUpVectorBar" "⥘" julia-latexsubs)
(puthash "\\LeftDownVectorBar" "⥙" julia-latexsubs)
(puthash "\\LeftTeeVector" "⥚" julia-latexsubs)
(puthash "\\RightTeeVector" "⥛" julia-latexsubs)
(puthash "\\RightUpTeeVector" "⥜" julia-latexsubs)
(puthash "\\RightDownTeeVector" "⥝" julia-latexsubs)
(puthash "\\DownLeftTeeVector" "⥞" julia-latexsubs)
(puthash "\\DownRightTeeVector" "⥟" julia-latexsubs)
(puthash "\\LeftUpTeeVector" "⥠" julia-latexsubs)
(puthash "\\LeftDownTeeVector" "⥡" julia-latexsubs)
(puthash "\\UpEquilibrium" "⥮" julia-latexsubs)
(puthash "\\ReverseUpEquilibrium" "⥯" julia-latexsubs)
(puthash "\\RoundImplies" "⥰" julia-latexsubs)
(puthash "\\Vvert" "⦀" julia-latexsubs)
(puthash "\\Elroang" "⦆" julia-latexsubs)
(puthash "\\Elzddfnc" "⦙" julia-latexsubs)
(puthash "\\Angle" "⦜" julia-latexsubs)
(puthash "\\Elzlpargt" "⦠" julia-latexsubs)
(puthash "\\obslash" "⦸" julia-latexsubs)
(puthash "\\boxdiag" "⧄" julia-latexsubs)
(puthash "\\boxbslash" "⧅" julia-latexsubs)
(puthash "\\boxast" "⧆" julia-latexsubs)
(puthash "\\boxcircle" "⧇" julia-latexsubs)
(puthash "\\ElzLap" "⧊" julia-latexsubs)
(puthash "\\Elzdefas" "⧋" julia-latexsubs)
(puthash "\\LeftTriangleBar" "⧏" julia-latexsubs)
(puthash "\\NotLeftTriangleBar" "⧏̸" julia-latexsubs)
(puthash "\\RightTriangleBar" "⧐" julia-latexsubs)
(puthash "\\NotRightTriangleBar" "⧐̸" julia-latexsubs)
(puthash "\\dualmap" "⧟" julia-latexsubs)
(puthash "\\shuffle" "⧢" julia-latexsubs)
(puthash "\\blacklozenge" "⧫" julia-latexsubs)
(puthash "\\RuleDelayed" "⧴" julia-latexsubs)
(puthash "\\bigodot" "⨀" julia-latexsubs)
(puthash "\\bigoplus" "⨁" julia-latexsubs)
(puthash "\\bigotimes" "⨂" julia-latexsubs)
(puthash "\\bigcupdot" "⨃" julia-latexsubs)
(puthash "\\biguplus" "⨄" julia-latexsubs)
(puthash "\\bigsqcap" "⨅" julia-latexsubs)
(puthash "\\bigsqcup" "⨆" julia-latexsubs)
(puthash "\\conjquant" "⨇" julia-latexsubs)
(puthash "\\disjquant" "⨈" julia-latexsubs)
(puthash "\\bigtimes" "⨉" julia-latexsubs)
(puthash "\\iiiint" "⨌" julia-latexsubs)
(puthash "\\intbar" "⨍" julia-latexsubs)
(puthash "\\intBar" "⨎" julia-latexsubs)
(puthash "\\clockoint" "⨏" julia-latexsubs)
(puthash "\\sqrint" "⨖" julia-latexsubs)
(puthash "\\intx" "⨘" julia-latexsubs)
(puthash "\\intcap" "⨙" julia-latexsubs)
(puthash "\\intcup" "⨚" julia-latexsubs)
(puthash "\\upint" "⨛" julia-latexsubs)
(puthash "\\lowint" "⨜" julia-latexsubs)
(puthash "\\plusdot" "⨥" julia-latexsubs)
(puthash "\\minusdot" "⨪" julia-latexsubs)
(puthash "\\ElzTimes" "⨯" julia-latexsubs)
(puthash "\\btimes" "⨲" julia-latexsubs)
(puthash "\\intprod" "⨼" julia-latexsubs)
(puthash "\\intprodr" "⨽" julia-latexsubs)
(puthash "\\amalg" "⨿" julia-latexsubs)
(puthash "\\ElzAnd" "⩓" julia-latexsubs)
(puthash "\\ElzOr" "⩔" julia-latexsubs)
(puthash "\\ElOr" "⩖" julia-latexsubs)
(puthash "\\perspcorrespond" "⩞" julia-latexsubs)
(puthash "\\Elzminhat" "⩟" julia-latexsubs)
(puthash "\\Equal" "⩵" julia-latexsubs)
(puthash "\\ddotseq" "⩷" julia-latexsubs)
(puthash "\\leqslant" "⩽" julia-latexsubs)
(puthash "\\nleqslant" "⩽̸" julia-latexsubs)
(puthash "\\geqslant" "⩾" julia-latexsubs)
(puthash "\\ngeqslant" "⩾̸" julia-latexsubs)
(puthash "\\lessapprox" "⪅" julia-latexsubs)
(puthash "\\gtrapprox" "⪆" julia-latexsubs)
(puthash "\\lneq" "⪇" julia-latexsubs)
(puthash "\\gneq" "⪈" julia-latexsubs)
(puthash "\\lnapprox" "⪉" julia-latexsubs)
(puthash "\\gnapprox" "⪊" julia-latexsubs)
(puthash "\\lesseqqgtr" "⪋" julia-latexsubs)
(puthash "\\gtreqqless" "⪌" julia-latexsubs)
(puthash "\\eqslantless" "⪕" julia-latexsubs)
(puthash "\\eqslantgtr" "⪖" julia-latexsubs)
(puthash "\\NestedLessLess" "⪡" julia-latexsubs)
(puthash "\\NotNestedLessLess" "⪡̸" julia-latexsubs)
(puthash "\\NestedGreaterGreater" "⪢" julia-latexsubs)
(puthash "\\NotNestedGreaterGreater" "⪢̸" julia-latexsubs)
(puthash "\\partialmeetcontraction" "⪣" julia-latexsubs)
(puthash "\\bumpeqq" "⪮" julia-latexsubs)
(puthash "\\preceq" "⪯" julia-latexsubs)
(puthash "\\npreceq" "⪯̸" julia-latexsubs)
(puthash "\\succeq" "⪰" julia-latexsubs)
(puthash "\\nsucceq" "⪰̸" julia-latexsubs)
(puthash "\\precneqq" "⪵" julia-latexsubs)
(puthash "\\succneqq" "⪶" julia-latexsubs)
(puthash "\\precapprox" "⪷" julia-latexsubs)
(puthash "\\succapprox" "⪸" julia-latexsubs)
(puthash "\\precnapprox" "⪹" julia-latexsubs)
(puthash "\\succnapprox" "⪺" julia-latexsubs)
(puthash "\\subseteqq" "⫅" julia-latexsubs)
(puthash "\\nsubseteqq" "⫅̸" julia-latexsubs)
(puthash "\\supseteqq" "⫆" julia-latexsubs)
(puthash "\\nsupseteqq" "⫆̸" julia-latexsubs)
(puthash "\\subsetneqq" "⫋" julia-latexsubs)
(puthash "\\supsetneqq" "⫌" julia-latexsubs)
(puthash "\\mlcp" "⫛" julia-latexsubs)
(puthash "\\forks" "⫝̸" julia-latexsubs)
(puthash "\\forksnot" "⫝" julia-latexsubs)
(puthash "\\dashV" "⫣" julia-latexsubs)
(puthash "\\Dashv" "⫤" julia-latexsubs)
(puthash "\\interleave" "⫴" julia-latexsubs)
(puthash "\\Elztdcol" "⫶" julia-latexsubs)
(puthash "\\_j" "\u2c7c" julia-latexsubs)
(puthash "\\^V" "\u2c7d" julia-latexsubs)
(puthash "\\openbracketleft" "〚" julia-latexsubs)
(puthash "\\openbracketright" "〛" julia-latexsubs)
(puthash "\\overbrace" "︷" julia-latexsubs)
(puthash "\\underbrace" "︸" julia-latexsubs)

(provide 'julia-mode)

;; Local Variables:
;; coding: utf-8
;; End:
;;; julia-mode.el ends here
