;
; Emacs mode for Julia
;

; USAGE
; =====

; Put the following code in your .emacs, site-load.el, or other relevant file
; (add-to-list 'load-path "path-to-julia-mode")
; (require 'julia-mode)


(defvar julia-mode-hook nil)

(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-mode))

;; define ignore-errors macro if it isn't present
;; (necessary for emacs 22 compatibility)
(when (not (fboundp 'ignore-errors))
  (defmacro ignore-errors (body) `(condition-case nil ,body (error nil))))

(defvar julia-mode-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?_ "w" table)   ; underscores in words
    (modify-syntax-entry ?@ "w" table)
    (modify-syntax-entry ?. "_" table)
    (modify-syntax-entry ?# "< 14" table)  ; # single-line and multiline start
    (modify-syntax-entry ?= ". 23bn" table)
    (modify-syntax-entry ?\n ">" table)  ; \n single-line comment end
    (modify-syntax-entry ?\{ "(} " table)
    (modify-syntax-entry ?\} "){ " table)
    (modify-syntax-entry ?\[ "(] " table)
    (modify-syntax-entry ?\] ")[ " table)
    (modify-syntax-entry ?\( "() " table)
    (modify-syntax-entry ?\) ")( " table)
    ;(modify-syntax-entry ?\\ "." table)  ; \ is an operator outside quotes
    (modify-syntax-entry ?'  "." table)  ; character quote or transpose
    (modify-syntax-entry ?\" "\"" table)
    (modify-syntax-entry ?` "\"" table)
    ;; (modify-syntax-entry ?\" "." table)
    (modify-syntax-entry ?? "." table)
    (modify-syntax-entry ?$ "." table)
    (modify-syntax-entry ?& "." table)
    (modify-syntax-entry ?* "." table)
    (modify-syntax-entry ?+ "." table)
    (modify-syntax-entry ?- "." table)
    (modify-syntax-entry ?< "." table)
    (modify-syntax-entry ?> "." table)
    (modify-syntax-entry ?% "." table)
    table)
  "Syntax table for `julia-mode'.")

;; syntax table that holds within strings
(defvar julia-mode-string-syntax-table
  (let ((table (make-syntax-table)))
    table)
  "Syntax table for `julia-mode'.")

;; disable " inside char quote
(defvar julia-mode-char-syntax-table
  (let ((table (make-syntax-table)))
    (modify-syntax-entry ?\" "." table)
    table)
  "Syntax table for `julia-mode'.")

(defconst julia-string-regex
  "\"[^\"]*?\\(\\(\\\\\\\\\\)*\\\\\"[^\"]*?\\)*\"")

(defconst julia-char-regex
  "\\(\\s(\\|\\s-\\|-\\|[,%=<>\\+*/?&|$!\\^~\\\\;:]\\|^\\)\\('\\(\\([^']*?[^\\\\]\\)\\|\\(\\\\\\\\\\)\\)'\\)")

(defconst julia-unquote-regex
  "\\(\\s(\\|\\s-\\|-\\|[,%=<>\\+*/?&|!\\^~\\\\;:]\\|^\\)\\($[a-zA-Z0-9_]+\\)")

(defconst julia-forloop-in-regex
  "for +.*[^
].* \\(in\\)\\(\\s-\\|$\\)+")

(defconst julia-font-lock-keywords
  (list '("\\<\\(\\|Uint\\(8\\|16\\|32\\|64\\|128\\)\\|Int\\(8\\|16\\|32\\|64\\|128\\)\\|BigInt\\|Integer\\|BigFloat\\|FloatingPoint\\|Float16\\|Float32\\|Float64\\|Complex128\\|Complex64\\|ComplexPair\\|Bool\\|Char\\|DataType\\|Number\\|Real\\|Int\\|Uint\\|Array\\|DArray\\|AbstractArray\\|AbstractVector\\|AbstractMatrix\\|AbstractSparseMatrix\\|SubArray\\|StridedArray\\|StridedVector\\|StridedMatrix\\|VecOrMat\\|StridedVecOrMat\\|DenseArray\\|Range\\|OrdinalRange\\|StepRange\\|UnitRange\\|FloatRange\\|SparseMatrixCSC\\|Tuple\\|NTuple\\|Symbol\\|Function\\|Vector\\|Matrix\\|Union\\|Type\\|Any\\|Complex\\|None\\|String\\|Ptr\\|Void\\|Exception\\|Task\\|Signed\\|Unsigned\\|Associative\\|Dict\\|IO\\|IOStream\\|Rational\\|Regex\\|RegexMatch\\|Set\\|IntSet\\|ASCIIString\\|UTF8String\\|ByteString\\|Expr\\|WeakRef\\|Nothing\\|ObjectIdDict\\|SubString\\)\\>" .
      font-lock-type-face)
    (cons
     (concat "\\<\\("
         (mapconcat
          'identity
          '("if" "else" "elseif" "while" "for" "begin" "end" "quote"
            "try" "catch" "return" "local" "abstract" "function" "macro" "ccall"
	    "finally" "typealias" "break" "continue" "type" "global" "@\\w+"
	    "module" "using" "import" "export" "const" "let" "bitstype" "do"
	    "baremodule" "importall" "immutable")
          "\\|") "\\)\\>")
     'font-lock-keyword-face)
    '("\\<\\(true\\|false\\|C_NULL\\|Inf\\|NaN\\|Inf32\\|NaN32\\|nothing\\)\\>" . font-lock-constant-face)
    (list julia-unquote-regex 2 'font-lock-constant-face)
    (list julia-char-regex 2 'font-lock-string-face)
    (list julia-forloop-in-regex 1 'font-lock-keyword-face)
    ;(list julia-string-regex 0 'font-lock-string-face)
))

(defconst julia-block-start-keywords
  (list "if" "while" "for" "begin" "try" "function" "type" "let" "macro"
	"quote" "do" "immutable"))

(defconst julia-block-other-keywords
  (list "else" "elseif"))

(defconst julia-block-end-keywords
  (list "end" "else" "elseif" "catch" "finally"))

(defun julia-member (item lst)
  (if (null lst)
      nil
    (or (equal item (car lst))
	(julia-member item (cdr lst)))))

(if (not (fboundp 'evenp))
    (defun evenp (x) (zerop (% x 2))))

(defun julia-find-comment-open (p0)
  (if (< (point) p0)
      nil
    (if (and (equal (char-after (point)) ?#)
	     (evenp (julia-strcount
		     (buffer-substring p0 (point)) ?\")))
	t
      (if (= (point) p0)
	  nil
	(progn (backward-char 1)
	       (julia-find-comment-open p0))))))

(defun julia-in-comment ()
  (save-excursion
    (julia-find-comment-open (line-beginning-position))))

(defun julia-strcount (str chr)
  (let ((i 0)
	(c 0))
    (while (< i (length str))
      (if (equal (elt str i) chr)
	  (setq c (+ c 1)))
      (setq i (+ i 1)))
    c))

(defun julia-in-brackets ()
  (let ((before (buffer-substring (line-beginning-position) (point))))
    (> (julia-strcount before ?[)
       (julia-strcount before ?]))))

(defun julia-at-keyword (kw-list)
  "Return the word at point if it matches any keyword in KW-LIST.
KW-LIST is a list of strings.  The word at point is not considered
a keyword if used as a field name, X.word, or quoted, :word."
  (and (or (= (point) 1)
	   (and (not (equal (char-before (point)) ?.))
		(not (equal (char-before (point)) ?:))))
       (not (julia-in-comment))
       (not (julia-in-brackets))
       (julia-member (current-word t) kw-list)))

;; if backward-sexp gives an error, move back 1 char to move over the '('
(defun julia-safe-backward-sexp ()
  (if (condition-case nil (backward-sexp) (error t))
      (ignore-errors (backward-char))))

(defun julia-last-open-block-pos (min)
  "Move back and return the position of the last open block, if one found.
Do not move back beyond position MIN."
  (let ((count 0))
    (while (not (or (> count 0) (<= (point) min)))
      (julia-safe-backward-sexp)
      (setq count
	    (cond ((julia-at-keyword julia-block-start-keywords)
		   (+ count 1))
		  ((and (equal (current-word t) "end")
			(not (julia-in-comment)) (not (julia-in-brackets)))
		   (- count 1))
		  (t count))))
    (if (> count 0)
	(point)
      nil)))

(defun julia-last-open-block (min)
  "Move back and return indentation level for last open block.
Do not move back beyond MIN."
  (let ((pos (julia-last-open-block-pos min)))
    (and pos
	 (progn
	   (goto-char pos)
	   (+ julia-basic-offset (current-indentation))))))

(defun julia-paren-indent ()
  "Return indent by last opening paren."
  (let* ((p (parse-partial-sexp
             (save-excursion
               ;; only indent by paren if the last open
               ;; paren is closer than the last open
               ;; block
               (or (julia-last-open-block-pos (point-min))
                   (point-min)))
             (progn (beginning-of-line)
                    (point))))
         (pos (cadr p)))
    (if (or (= 0 (car p)) (null pos))
        nil
      (progn (goto-char pos) (+ 1 (current-column))))))

(defun julia-indent-line ()
  "Indent current line of julia code."
  (interactive)
;  (save-excursion
    (end-of-line)
    (indent-line-to
     (or (save-excursion (ignore-errors (julia-paren-indent)))
         (save-excursion
           (let ((endtok (progn
                           (beginning-of-line)
                           (forward-to-indentation 0)
                           (julia-at-keyword julia-block-end-keywords))))
             (ignore-errors (+ (julia-last-open-block (point-min))
                           (if endtok (- julia-basic-offset) 0)))))
	 ;; previous line ends in =
	 (save-excursion
	   (if (and (not (equal (point-min) (line-beginning-position)))
		    (progn
		      (forward-line -1)
		      (end-of-line) (backward-char 1)
		      (equal (char-after (point)) ?=)))
	       (+ julia-basic-offset (current-indentation))
	     nil))
	 ;; take same indentation as previous line
	 (save-excursion (forward-line -1)
			 (current-indentation))
         0))
    (when (julia-at-keyword julia-block-end-keywords)
      (forward-word 1)))

(defalias 'julia-mode-prog-mode
  (if (fboundp 'prog-mode)
      'prog-mode
    'fundamental-mode))

;;;###autoload
(define-derived-mode julia-mode julia-mode-prog-mode "Julia"
  "Major mode for editing julia code."
  (set-syntax-table julia-mode-syntax-table)
  (set (make-local-variable 'comment-start) "# ")
  (set (make-local-variable 'comment-start-skip) "#+\\s-*")
  (set (make-local-variable 'font-lock-defaults) '(julia-font-lock-keywords))
  (set (make-local-variable 'font-lock-syntactic-keywords)
       (list
	(list "\\(\\\\\\)\\s-*\".*?\"" 1 julia-mode-char-syntax-table)))
  (set (make-local-variable 'font-lock-syntactic-keywords)
        (list
 	(list julia-char-regex 2
 	      julia-mode-char-syntax-table)
        (list julia-string-regex 0
              julia-mode-string-syntax-table)
	))
  (set (make-local-variable 'indent-line-function) 'julia-indent-line)
  (set (make-local-variable 'julia-basic-offset) 4)
  (setq indent-tabs-mode nil)
  (setq imenu-generic-expression julia-imenu-generic-expression)
  (imenu-add-to-menubar "Imenu"))

;;; IMENU
(defvar julia-imenu-generic-expression
  ;; don't use syntax classes, screws egrep
  '(("Function (_)" "[ \t]*function[ \t]+\\(_[^ \t\n]*\\)" 1)
    ("Function" "^[ \t]*function[ \t]+\\([^_][^\t\n]*\\)" 1)
    ("Const" "[ \t]*const \\([^ \t\n]*\\)" 1)
    ("Type"  "^[ \t]*[a-zA-Z0-9_]*type[a-zA-Z0-9_]* \\([^ \t\n]*\\)" 1)
    ("Require"      " *\\(\\brequire\\)(\\([^ \t\n)]*\\)" 2)
    ("Include"      " *\\(\\binclude\\)(\\([^ \t\n)]*\\)" 2)
    ;; ("Classes" "^.*setClass(\\(.*\\)," 1)
    ;; ("Coercions" "^.*setAs(\\([^,]+,[^,]*\\)," 1) ; show from and to
    ;; ("Generics" "^.*setGeneric(\\([^,]*\\)," 1)
    ;; ("Methods" "^.*set\\(Group\\|Replace\\)?Method(\"\\(.+\\)\"," 2)
    ;; ;;[ ]*\\(signature=\\)?(\\(.*,?\\)*\\)," 1)
    ;; ;;
    ;; ;;("Other" "^\\(.+\\)\\s-*<-[ \t\n]*[^\\(function\\|read\\|.*data\.frame\\)]" 1)
    ;; ("Package" "^.*\\(library\\|require\\)(\\(.*\\)," 2)
    ;; ("Data" "^\\(.+\\)\\s-*<-[ \t\n]*\\(read\\|.*data\.frame\\).*(" 1)))
    ))

(setq latexsubs (make-hash-table :test 'equal))
(defun latexcharp (c)
  (or (= c ?_) (and (>= c ?a) (<= c ?z)) (and (>= c ?A) (<= c ?Z))))
(defun latexsub (arg)
  "Perform a LaTeX-like Unicode symbol substitution."
  (interactive "*i")
  (let (end-point (orig-point (point)))
    (while (and (not (eobp)) (latexcharp (char-after)))
      (forward-char))
    (setq end-point (point))
    (goto-char orig-point)
    (while (and (not (bobp)) (latexcharp (char-before)))
      (backward-char))
    (if (and (not (bobp)) (= ?\\ (char-before)))
        (progn
          (backward-char)
          (let ((sub (gethash (buffer-substring (point) end-point) latexsubs)))
            (if sub
                (progn
                  (delete-region (point) end-point)
                  (insert sub))
              (goto-char orig-point))))
      (goto-char orig-point))))

(defun latexsub-or-indent (arg)
  "Either indent according to mode or perform a LaTeX-like symbol substution"
  (interactive "*i")
  (if (latexsub arg)
      (indent-according-to-mode)))
(define-key julia-mode-map (kbd "TAB") 'latexsub-or-indent)

; LaTeX-like symbol substitutions, equivalent to those in the Julia REPL,
; generated by:
; for (k, v) in Base.REPLCompletions.latex_symbols
;    println("(puthash \"$(escape_string(k))\" \"$(escape_string(v))\" latexsubs)")
; end
(puthash "\\guilsinglright" "›" latexsubs)
(puthash "\\blacktriangleright" "▸" latexsubs)
(puthash "\\Re" "ℜ" latexsubs)
(puthash "\\pitchfork" "⋔" latexsubs)
(puthash "\\Elzinglst" "ʖ" latexsubs)
(puthash "\\urcorner" "⌝" latexsubs)
(puthash "\\pi" "π" latexsubs)
(puthash "\\nless" "≮" latexsubs)
(puthash "\\sqsubseteq" "⊑" latexsubs)
(puthash "\\Updownarrow" "⇕" latexsubs)
(puthash "\\nrightarrow" "↛" latexsubs)
(puthash "\\Theta" "Θ" latexsubs)
(puthash "\\rightmoon" "☾" latexsubs)
(puthash "\\upsilon" "υ" latexsubs)
(puthash "\\copyright" "©" latexsubs)
(puthash "\\smile" "⌣" latexsubs)
(puthash "\\backsimeq" "⋍" latexsubs)
(puthash "\\BbbPi" "ℿ" latexsubs)
(puthash "\\lq" "‘" latexsubs)
(puthash "\\perp" "⊥" latexsubs)
(puthash "\\textnrleg" "ƞ" latexsubs)
(puthash "\\llcorner" "⌞" latexsubs)
(puthash "\\bigtimes" "⨉" latexsubs)
(puthash "\\circleddash" "⊝" latexsubs)
(puthash "\\leftharpoondown" "↽" latexsubs)
(puthash "\\alpha" "α" latexsubs)
(puthash "\\between" "≬" latexsubs)
(puthash "\\frown" "⌢" latexsubs)
(puthash "\\RoundImplies" "⥰" latexsubs)
(puthash "\\precneqq" "⪵" latexsubs)
(puthash "\\nsupseteq" "⊉" latexsubs)
(puthash "\\iota" "ι" latexsubs)
(puthash "\\overbrace" "︷" latexsubs)
(puthash "\\rightharpoondown" "⇁" latexsubs)
(puthash "\\tilde" "̃" latexsubs)
(puthash "\\rightleftarrows" "⇄" latexsubs)
(puthash "\\succapprox" "⪸" latexsubs)
(puthash "\\Rsh" "↱" latexsubs)
(puthash "\\fdiagovnearrow" "⤯" latexsubs)
(puthash "\\original" "⊶" latexsubs)
(puthash "\\nBumpeq" "≎̸" latexsubs)
(puthash "\\nleftrightarrow" "↮" latexsubs)
(puthash "\\clockoint" "⨏" latexsubs)
(puthash "\\Im" "ℑ" latexsubs)
(puthash "\\Elzrarrx" "⥇" latexsubs)
(puthash "\\leo" "♌" latexsubs)
(puthash "\\DownArrowBar" "⤓" latexsubs)
(puthash "\\surd" "√" latexsubs)
(puthash "\\ge" "≥" latexsubs)
(puthash "\\amalg" "⨿" latexsubs)
(puthash "\\ElOr" "⩖" latexsubs)
(puthash "\\uparrow" "↑" latexsubs)
(puthash "\\Game" "⅁" latexsubs)
(puthash "\\sterling" "£" latexsubs)
(puthash "\\NestedGreaterGreater" "⪢" latexsubs)
(puthash "\\bumpeqq" "⪮" latexsubs)
(puthash "\\nVDash" "⊯" latexsubs)
(puthash "\\leftarrowtriangle" "⇽" latexsubs)
(puthash "\\lnsim" "⋦" latexsubs)
(puthash "\\yen" "¥" latexsubs)
(puthash "\\theta" "θ" latexsubs)
(puthash "\\gnapprox" "⪊" latexsubs)
(puthash "\\male" "♂" latexsubs)
(puthash "\\LeftUpVectorBar" "⥘" latexsubs)
(puthash "\\NotLeftTriangleBar" "⧏̸" latexsubs)
(puthash "\\nRightarrow" "⇏" latexsubs)
(puthash "\\Elzsqspne" "⋥" latexsubs)
(puthash "\\forks" "⫝̸" latexsubs)
(puthash "\\Alpha" "Α" latexsubs)
(puthash "\\backepsilon" "϶" latexsubs)
(puthash "\\psi" "ψ" latexsubs)
(puthash "\\ng" "ŋ" latexsubs)
(puthash "\\Sampi" "Ϡ" latexsubs)
(puthash "\\textperthousand" "‰" latexsubs)
(puthash "\\l" "ł" latexsubs)
(puthash "\\star" "⋆" latexsubs)
(puthash "\\Elzbtdl" "ɬ" latexsubs)
(puthash "\\Downarrow" "⇓" latexsubs)
(puthash "\\lvertneqq" "≨︀" latexsubs)
(puthash "\\S" "§" latexsubs)
(puthash "\\NotLessLess" "≪̸" latexsubs)
(puthash "\\omega" "ω" latexsubs)
(puthash "\\NotSquareSubset" "⊏̸" latexsubs)
(puthash "\\boxcircle" "⧇" latexsubs)
(puthash "\\Bumpeq" "≎" latexsubs)
(puthash "\\gtreqless" "⋛" latexsubs)
(puthash "\\daleth" "ℸ" latexsubs)
(puthash "\\recorder" "⌕" latexsubs)
(puthash "\\Elroang" "⦆" latexsubs)
(puthash "\\forksnot" "⫝" latexsubs)
(puthash "\\Angle" "⦜" latexsubs)
(puthash "\\shuffle" "⧢" latexsubs)
(puthash "\\ReverseUpEquilibrium" "⥯" latexsubs)
(puthash "\\Elzxrat" "℞" latexsubs)
(puthash "\\Elztesh" "ʧ" latexsubs)
(puthash "\\Elzsbrhr" "˒" latexsubs)
(puthash "\\rightleftharpoons" "⇌" latexsubs)
(puthash "\\Elzrtln" "ɳ" latexsubs)
(puthash "\\checkmark" "✓" latexsubs)
(puthash "\\Elzsqfnw" "┙" latexsubs)
(puthash "\\Elzxh" "ħ" latexsubs)
(puthash "\\nsubseteqq" "⫅̸" latexsubs)
(puthash "\\mars" "♂" latexsubs)
(puthash "\\ngtr" "≯" latexsubs)
(puthash "\\hksearow" "⤥" latexsubs)
(puthash "\\lesssim" "≲" latexsubs)
(puthash "\\obar" "⌽" latexsubs)
(puthash "\\Colon" "∷" latexsubs)
(puthash "\\sagittarius" "♐" latexsubs)
(puthash "\\dot" "̇" latexsubs)
(puthash "\\Omega" "Ω" latexsubs)
(puthash "\\looparrowright" "↬" latexsubs)
(puthash "\\Vert" "‖" latexsubs)
(puthash "\\fdiagovrdiag" "⤬" latexsubs)
(puthash "\\ngeqslant" "⩾̸" latexsubs)
(puthash "\\perspcorrespond" "⩞" latexsubs)
(puthash "\\twoheadrightarrow" "↠" latexsubs)
(puthash "\\beta" "β" latexsubs)
(puthash "\\c" "̧" latexsubs)
(puthash "\\Elzrtlr" "ɽ" latexsubs)
(puthash "\\approxnotequal" "≆" latexsubs)
(puthash "\\sqrt" "√" latexsubs)
(puthash "\\plusdot" "⨥" latexsubs)
(puthash "\\bigodot" "⨀" latexsubs)
(puthash "\\subsetneqq" "⫋" latexsubs)
(puthash "\\neg" "¬" latexsubs)
(puthash "\\Elzreglst" "ʕ" latexsubs)
(puthash "\\barwedge" "⌅" latexsubs)
(puthash "\\Elzrvbull" "◘" latexsubs)
(puthash "\\Rightarrow" "⇒" latexsubs)
(puthash "\\textasciicaron" "ˇ" latexsubs)
(puthash "\\Cap" "⋒" latexsubs)
(puthash "\\aleph" "ℵ" latexsubs)
(puthash "\\xi" "ξ" latexsubs)
(puthash "\\lessapprox" "⪅" latexsubs)
(puthash "\\ddddot" "⃜" latexsubs)
(puthash "\\longrightarrow" "⟶" latexsubs)
(puthash "\\Elzrais" "˔" latexsubs)
(puthash "\\lmoustache" "⎰" latexsubs)
(puthash "\\pm" "±" latexsubs)
(puthash "\\prec" "≺" latexsubs)
(puthash "\\disjquant" "⨈" latexsubs)
(puthash "\\DH" "Ð" latexsubs)
(puthash "\\openbracketright" "〛" latexsubs)
(puthash "\\Elzsqfr" "◨" latexsubs)
(puthash "\\downharpoonleft" "⇃" latexsubs)
(puthash "\\phi" "ϕ" latexsubs)
(puthash "\\lozenge" "◊" latexsubs)
(puthash "\\L" "Ł" latexsubs)
(puthash "\\ni" "∋" latexsubs)
(puthash "\\subseteqq" "⫅" latexsubs)
(puthash "\\texttildelow" "˜" latexsubs)
(puthash "\\heartsuit" "♡" latexsubs)
(puthash "\\Elztrnsa" "ɒ" latexsubs)
(puthash "\\subset" "⊂" latexsubs)
(puthash "\\venus" "♀" latexsubs)
(puthash "\\thinspace" " " latexsubs)
(puthash "\\fallingdotseq" "≒" latexsubs)
(puthash "\\partialmeetcontraction" "⪣" latexsubs)
(puthash "\\NotNestedLessLess" "⪡̸" latexsubs)
(puthash "\\approx" "≈" latexsubs)
(puthash "\\gtrless" "≷" latexsubs)
(puthash "\\ntriangleleft" "⋪" latexsubs)
(puthash "\\partial" "∂" latexsubs)
(puthash "\\pluto" "♇" latexsubs)
(puthash "\\kappa" "κ" latexsubs)
(puthash "\\textTheta" "ϴ" latexsubs)
(puthash "\\Vvdash" "⊪" latexsubs)
(puthash "\\hspace" " " latexsubs)
(puthash "\\leqslant" "⩽" latexsubs)
(puthash "\\questeq" "≟" latexsubs)
(puthash "\\wp" "℘" latexsubs)
(puthash "\\gamma" "γ" latexsubs)
(puthash "\\NotGreaterGreater" "≫̸" latexsubs)
(puthash "\\Doteq" "≑" latexsubs)
(puthash "\\Elzlmrk" "ː" latexsubs)
(puthash "\\Elzdlcorn" "⎣" latexsubs)
(puthash "\\nsubset" "⊄" latexsubs)
(puthash "\\Equal" "⩵" latexsubs)
(puthash "\\bkarow" "⤍" latexsubs)
(puthash "\\intcup" "⨚" latexsubs)
(puthash "\\P" "¶" latexsubs)
(puthash "\\lneq" "⪇" latexsubs)
(puthash "\\napprox" "≉" latexsubs)
(puthash "\\Elztrnm" "ɯ" latexsubs)
(puthash "\\bigstar" "★" latexsubs)
(puthash "\\lesseqgtr" "⋚" latexsubs)
(puthash "\\ngeq" "≱" latexsubs)
(puthash "\\varnothing" "∅" latexsubs)
(puthash "\\supseteq" "⊇" latexsubs)
(puthash "\\eta" "η" latexsubs)
(puthash "\\varrho" "ϱ" latexsubs)
(puthash "\\neptune" "♆" latexsubs)
(puthash "\\Vdash" "⊩" latexsubs)
(puthash "\\dots" "…" latexsubs)
(puthash "\\longleftrightarrow" "⟷" latexsubs)
(puthash "\\gemini" "♊" latexsubs)
(puthash "\\nsupset" "⊅" latexsubs)
(puthash "\\supsetneqq" "⫌" latexsubs)
(puthash "\\bigtriangleup" "△" latexsubs)
(puthash "\\diagup" "╱" latexsubs)
(puthash "\\nexists" "∄" latexsubs)
(puthash "\\image" "⊷" latexsubs)
(puthash "\\underbrace" "︸" latexsubs)
(puthash "\\boxplus" "⊞" latexsubs)
(puthash "\\Zeta" "Ζ" latexsubs)
(puthash "\\texthvlig" "ƕ" latexsubs)
(puthash "\\OE" "Œ" latexsubs)
(puthash "\\circledcirc" "⊚" latexsubs)
(puthash "\\capricornus" "♑" latexsubs)
(puthash "\\towa" "⤪" latexsubs)
(puthash "\\in" "∈" latexsubs)
(puthash "\\chi" "χ" latexsubs)
(puthash "\\imath" "ı" latexsubs)
(puthash "\\Elzcirfl" "◐" latexsubs)
(puthash "\\Elzrttrnr" "ɻ" latexsubs)
(puthash "\\Xi" "Ξ" latexsubs)
(puthash "\\RightUpVectorBar" "⥔" latexsubs)
(puthash "\\veebar" "⊻" latexsubs)
(puthash "\\nsuccsim" "≿̸" latexsubs)
(puthash "\\verymuchless" "⋘" latexsubs)
(puthash "\\textphi" "ɸ" latexsubs)
(puthash "\\Elztrnt" "ʇ" latexsubs)
(puthash "\\triangleq" "≜" latexsubs)
(puthash "\\Beta" "Β" latexsubs)
(puthash "\\ast" "∗" latexsubs)
(puthash "\\bigsqcup" "⨆" latexsubs)
(puthash "\\Elzbar" "̶" latexsubs)
(puthash "\\nequiv" "≢" latexsubs)
(puthash "\\ncong" "≇" latexsubs)
(puthash "\\Elzrtls" "ʂ" latexsubs)
(puthash "\\dddot" "⃛" latexsubs)
(puthash "\\dotminus" "∸" latexsubs)
(puthash "\\oint" "∮" latexsubs)
(puthash "\\circlearrowleft" "↺" latexsubs)
(puthash "\\diamondsuit" "♢" latexsubs)
(puthash "\\nLeftarrow" "⇍" latexsubs)
(puthash "\\Elzpscrv" "ʋ" latexsubs)
(puthash "\\Elzltlmr" "ɱ" latexsubs)
(puthash "\\acute" "́" latexsubs)
(puthash "\\Elzddfnc" "⦙" latexsubs)
(puthash "\\bigtriangledown" "▽" latexsubs)
(puthash "\\Longleftarrow" "⟸" latexsubs)
(puthash "\\nsucc" "⊁" latexsubs)
(puthash "\\square" "□" latexsubs)
(puthash "\\succ" "≻" latexsubs)
(puthash "\\neovnwarrow" "⤱" latexsubs)
(puthash "\\Elzfhr" "ɾ" latexsubs)
(puthash "\\langle" "〈" latexsubs)
(puthash "\\DownRightVectorBar" "⥗" latexsubs)
(puthash "\\clubsuit" "♣" latexsubs)
(puthash "\\Stigma" "Ϛ" latexsubs)
(puthash "\\rightangle" "∟" latexsubs)
(puthash "\\backsim" "∽" latexsubs)
(puthash "\\Elzsblhr" "˓" latexsubs)
(puthash "\\downdownarrows" "⇊" latexsubs)
(puthash "\\lowint" "⨜" latexsubs)
(puthash "\\Elzminhat" "⩟" latexsubs)
(puthash "\\varphi" "φ" latexsubs)
(puthash "\\blacklozenge" "⧫" latexsubs)
(puthash "\\Tau" "Τ" latexsubs)
(puthash "\\looparrowleft" "↫" latexsubs)
(puthash "\\beth" "ℶ" latexsubs)
(puthash "\\nsim" "≁" latexsubs)
(puthash "\\ocirc" "̊" latexsubs)
(puthash "\\div" "÷" latexsubs)
(puthash "\\Elztrnmlr" "ɰ" latexsubs)
(puthash "\\bigcupdot" "⨃" latexsubs)
(puthash "\\bbsum" "⅀" latexsubs)
(puthash "\\iiint" "∭" latexsubs)
(puthash "\\cancer" "♋" latexsubs)
(puthash "\\sqcup" "⊔" latexsubs)
(puthash "\\Longrightarrow" "⟹" latexsubs)
(puthash "\\subsetneq" "⊊" latexsubs)
(puthash "\\dagger" "†" latexsubs)
(puthash "\\textdoublepipe" "ǂ" latexsubs)
(puthash "\\textquotedblright" "”" latexsubs)
(puthash "\\notlessgreater" "≸" latexsubs)
(puthash "\\rightrightarrows" "⇉" latexsubs)
(puthash "\\DownRightTeeVector" "⥟" latexsubs)
(puthash "\\textturnk" "ʞ" latexsubs)
(puthash "\\allequal" "≌" latexsubs)
(puthash "\\female" "♀" latexsubs)
(puthash "\\cdotp" "·" latexsubs)
(puthash "\\Elzcirfb" "◒" latexsubs)
(puthash "\\ntrianglerighteq" "⋭" latexsubs)
(puthash "\\ElzTimes" "⨯" latexsubs)
(puthash "\\blacktriangle" "▴" latexsubs)
(puthash "\\saturn" "♄" latexsubs)
(puthash "\\DownLeftRightVector" "⥐" latexsubs)
(puthash "\\Elzverti" "ˌ" latexsubs)
(puthash "\\curlyeqsucc" "⋟" latexsubs)
(puthash "\\DownLeftTeeVector" "⥞" latexsubs)
(puthash "\\Elzpes" "₧" latexsubs)
(puthash "\\rdiagovfdiag" "⤫" latexsubs)
(puthash "\\Elzxl" "̵" latexsubs)
(puthash "\\mapsto" "↦" latexsubs)
(puthash "\\maltese" "✠" latexsubs)
(puthash "\\hslash" "ℏ" latexsubs)
(puthash "\\blacksquare" "■" latexsubs)
(puthash "\\upuparrows" "⇈" latexsubs)
(puthash "\\taurus" "♉" latexsubs)
(puthash "\\vDash" "⊨" latexsubs)
(puthash "\\conjquant" "⨇" latexsubs)
(puthash "\\sim" "∼" latexsubs)
(puthash "\\RuleDelayed" "⧴" latexsubs)
(puthash "\\sum" "∑" latexsubs)
(puthash "\\aquarius" "♒" latexsubs)
(puthash "\\ggg" "⋙" latexsubs)
(puthash "\\uranus" "♅" latexsubs)
(puthash "\\rightthreetimes" "⋌" latexsubs)
(puthash "\\ElzrLarr" "⥄" latexsubs)
(puthash "\\O" "Ø" latexsubs)
(puthash "\\nbumpeq" "≏̸" latexsubs)
(puthash "\\dashv" "⊣" latexsubs)
(puthash "\\curlywedge" "⋏" latexsubs)
(puthash "\\gg" "≫" latexsubs)
(puthash "\\sqsupset" "⊐" latexsubs)
(puthash "\\nprec" "⊀" latexsubs)
(puthash "\\diamond" "⋄" latexsubs)
(puthash "\\leftrightarrows" "⇆" latexsubs)
(puthash "\\LeftUpTeeVector" "⥠" latexsubs)
(puthash "\\eighthnote" "♪" latexsubs)
(puthash "\\risingdotseq" "≓" latexsubs)
(puthash "\\RightUpTeeVector" "⥜" latexsubs)
(puthash "\\textonequarter" "¼" latexsubs)
(puthash "\\iint" "∬" latexsubs)
(puthash "\\nleqslant" "⩽̸" latexsubs)
(puthash "\\textexclamdown" "¡" latexsubs)
(puthash "\\nprecsim" "≾̸" latexsubs)
(puthash "\\btimes" "⨲" latexsubs)
(puthash "\\oe" "œ" latexsubs)
(puthash "\\forall" "∀" latexsubs)
(puthash "\\textthreequarters" "¾" latexsubs)
(puthash "\\Elztrna" "ɐ" latexsubs)
(puthash "\\rightarrowtriangle" "⇾" latexsubs)
(puthash "\\supset" "⊃" latexsubs)
(puthash "\\equiv" "≡" latexsubs)
(puthash "\\sharp" "♯" latexsubs)
(puthash "\\epsilon" "ϵ" latexsubs)
(puthash "\\ae" "æ" latexsubs)
(puthash "\\infty" "∞" latexsubs)
(puthash "\\dualmap" "⧟" latexsubs)
(puthash "\\bigotimes" "⨂" latexsubs)
(puthash "\\eqslantgtr" "⪖" latexsubs)
(puthash "\\lrcorner" "⌟" latexsubs)
(puthash "\\nwarrow" "↖" latexsubs)
(puthash "\\leqq" "≦" latexsubs)
(puthash "\\lfloor" "⌊" latexsubs)
(puthash "\\Elzdshfnc" "┆" latexsubs)
(puthash "\\rightsquigarrow" "↝" latexsubs)
(puthash "\\leftarrow" "←" latexsubs)
(puthash "\\sphericalangle" "∢" latexsubs)
(puthash "\\boxtimes" "⊠" latexsubs)
(puthash "\\hkswarow" "⤦" latexsubs)
(puthash "\\ElzOr" "⩔" latexsubs)
(puthash "\\interleave" "⫴" latexsubs)
(puthash "\\complement" "∁" latexsubs)
(puthash "\\Ddownarrow" "⤋" latexsubs)
(puthash "\\neqsim" "≂̸" latexsubs)
(puthash "\\Koppa" "Ϟ" latexsubs)
(puthash "\\angle" "∠" latexsubs)
(puthash "\\Eta" "Η" latexsubs)
(puthash "\\ll" "≪" latexsubs)
(puthash "\\vartriangle" "▵" latexsubs)
(puthash "\\Leftarrow" "⇐" latexsubs)
(puthash "\\asymp" "≍" latexsubs)
(puthash "\\times" "×" latexsubs)
(puthash "\\wr" "≀" latexsubs)
(puthash "\\twoheadrightarrowtail" "⤖" latexsubs)
(puthash "\\ddotseq" "⩷" latexsubs)
(puthash "\\ss" "ß" latexsubs)
(puthash "\\intcap" "⨙" latexsubs)
(puthash "\\openbracketleft" "〚" latexsubs)
(puthash "\\triangleleft" "◃" latexsubs)
(puthash "\\nvdash" "⊬" latexsubs)
(puthash "\\oiiint" "∰" latexsubs)
(puthash "\\precnsim" "⋨" latexsubs)
(puthash "\\UpEquilibrium" "⥮" latexsubs)
(puthash "\\Elztrnrl" "ɺ" latexsubs)
(puthash "\\aries" "♈" latexsubs)
(puthash "\\intercal" "⊺" latexsubs)
(puthash "\\ntrianglelefteq" "⋬" latexsubs)
(puthash "\\bigvee" "⋁" latexsubs)
(puthash "\\minus" "−" latexsubs)
(puthash "\\nleftarrow" "↚" latexsubs)
(puthash "\\mho" "℧" latexsubs)
(puthash "\\bigwedge" "⋀" latexsubs)
(puthash "\\Elzdyogh" "ʤ" latexsubs)
(puthash "\\curlyvee" "⋎" latexsubs)
(puthash "\\eth" "ð" latexsubs)
(puthash "\\lesseqqgtr" "⪋" latexsubs)
(puthash "\\scorpio" "♏" latexsubs)
(puthash "\\Elzrh" "̢" latexsubs)
(puthash "\\upharpoonright" "↿" latexsubs)
(puthash "\\lessdot" "⋖" latexsubs)
(puthash "\\textordfeminine" "ª" latexsubs)
(puthash "\\coprod" "∐" latexsubs)
(puthash "\\aa" "å" latexsubs)
(puthash "\\dblarrowupdown" "⇅" latexsubs)
(puthash "\\cupdot" "⊍" latexsubs)
(puthash "\\Lsh" "↰" latexsubs)
(puthash "\\Elzcirfr" "◑" latexsubs)
(puthash "\\Elzrtlt" "ʈ" latexsubs)
(puthash "\\trianglelefteq" "⊴" latexsubs)
(puthash "\\degree" "°" latexsubs)
(puthash "\\ddot" "̈" latexsubs)
(puthash "\\ddagger" "‡" latexsubs)
(puthash "\\bigcap" "⋂" latexsubs)
(puthash "\\Elzpbgam" "ɤ" latexsubs)
(puthash "\\circeq" "≗" latexsubs)
(puthash "\\Phi" "Φ" latexsubs)
(puthash "\\guilsinglleft" "‹" latexsubs)
(puthash "\\AE" "Æ" latexsubs)
(puthash "\\check" "̌" latexsubs)
(puthash "\\intx" "⨘" latexsubs)
(puthash "\\Upsilon" "Υ" latexsubs)
(puthash "\\Elzinvw" "ʍ" latexsubs)
(puthash "\\LeftUpDownVector" "⥑" latexsubs)
(puthash "\\Elzinvv" "ʌ" latexsubs)
(puthash "\\Dashv" "⫤" latexsubs)
(puthash "\\Elzdefas" "⧋" latexsubs)
(puthash "\\ltimes" "⋉" latexsubs)
(puthash "\\leftrightarrow" "↔" latexsubs)
(puthash "\\Mapsto" "⤇" latexsubs)
(puthash "\\mid" "∣" latexsubs)
(puthash "\\hookleftarrow" "↩" latexsubs)
(puthash "\\LeftTriangleBar" "⧏" latexsubs)
(puthash "\\swarrow" "↙" latexsubs)
(puthash "\\textvisiblespace" "␣" latexsubs)
(puthash "\\bar" "̄" latexsubs)
(puthash "\\natural" "♮" latexsubs)
(puthash "\\mp" "∓" latexsubs)
(puthash "\\subseteq" "⊆" latexsubs)
(puthash "\\NG" "Ŋ" latexsubs)
(puthash "\\LeftRightVector" "⥎" latexsubs)
(puthash "\\gtreqqless" "⪌" latexsubs)
(puthash "\\Longleftrightarrow" "⟺" latexsubs)
(puthash "\\vdots" "⋮" latexsubs)
(puthash "\\Elzltln" "ɲ" latexsubs)
(puthash "\\gimel" "ℷ" latexsubs)
(puthash "\\iiiint" "⨌" latexsubs)
(puthash "\\TH" "Þ" latexsubs)
(puthash "\\clwintegral" "∱" latexsubs)
(puthash "\\Lleftarrow" "⇚" latexsubs)
(puthash "\\hat" "̂" latexsubs)
(puthash "\\nearrow" "↗" latexsubs)
(puthash "\\vartheta" "ϑ" latexsubs)
(puthash "\\Iota" "Ι" latexsubs)
(puthash "\\th" "þ" latexsubs)
(puthash "\\Elzvrecto" "▯" latexsubs)
(puthash "\\kernelcontraction" "∻" latexsubs)
(puthash "\\ntriangleright" "⋫" latexsubs)
(puthash "\\breve" "̆" latexsubs)
(puthash "\\succeq" "⪰" latexsubs)
(puthash "\\enspace" " " latexsubs)
(puthash "\\nwovnearrow" "⤲" latexsubs)
(puthash "\\bigcirc" "○" latexsubs)
(puthash "\\sigma" "σ" latexsubs)
(puthash "\\leftharpoonup" "↼" latexsubs)
(puthash "\\textasciiacute" "´" latexsubs)
(puthash "\\int" "∫" latexsubs)
(puthash "\\curlyeqprec" "⋞" latexsubs)
(puthash "\\Elztdcol" "⫶" latexsubs)
(puthash "\\neovsearrow" "⤮" latexsubs)
(puthash "\\Leftrightarrow" "⇔" latexsubs)
(puthash "\\lceil" "⌈" latexsubs)
(puthash "\\UpArrowBar" "⤒" latexsubs)
(puthash "\\ne" "≠" latexsubs)
(puthash "\\varsubsetneqq" "⊊︀" latexsubs)
(puthash "\\bullet" "•" latexsubs)
(puthash "\\boxbslash" "⧅" latexsubs)
(puthash "\\precnapprox" "⪹" latexsubs)
(puthash "\\precapprox" "⪷" latexsubs)
(puthash "\\curvearrowright" "↷" latexsubs)
(puthash "\\top" "⊤" latexsubs)
(puthash "\\Elztrny" "ʎ" latexsubs)
(puthash "\\Elztrnr" "ɹ" latexsubs)
(puthash "\\blacktriangledown" "▾" latexsubs)
(puthash "\\Elzhlmrk" "ˑ" latexsubs)
(puthash "\\rasp" "ʼ" latexsubs)
(puthash "\\downharpoonright" "⇂" latexsubs)
(puthash "\\sqsubset" "⊏" latexsubs)
(puthash "\\succsim" "≿" latexsubs)
(puthash "\\dashV" "⫣" latexsubs)
(puthash "\\Elzopeno" "ɔ" latexsubs)
(puthash "\\emdash" "—" latexsubs)
(puthash "\\delta" "δ" latexsubs)
(puthash "\\rfloor" "⌋" latexsubs)
(puthash "\\eqslantless" "⪕" latexsubs)
(puthash "\\Elzverts" "ˈ" latexsubs)
(puthash "\\eqcolon" "≕" latexsubs)
(puthash "\\nsubseteq" "⊈" latexsubs)
(puthash "\\wedge" "∧" latexsubs)
(puthash "\\cdots" "⋯" latexsubs)
(puthash "\\spadesuit" "♠" latexsubs)
(puthash "\\tildetrpl" "≋" latexsubs)
(puthash "\\leftrightsquigarrow" "↭" latexsubs)
(puthash "\\dbkarow" "⤏" latexsubs)
(puthash "\\Sigma" "Σ" latexsubs)
(puthash "\\longmapsto" "⟼" latexsubs)
(puthash "\\DownArrowUpArrow" "⇵" latexsubs)
(puthash "\\intbar" "⨍" latexsubs)
(puthash "\\npreceq" "⪯̸" latexsubs)
(puthash "\\virgo" "♍" latexsubs)
(puthash "\\boxast" "⧆" latexsubs)
(puthash "\\Elzsbbrg" "̪" latexsubs)
(puthash "\\drbkarrow" "⤐" latexsubs)
(puthash "\\ell" "ℓ" latexsubs)
(puthash "\\tau" "τ" latexsubs)
(puthash "\\Vvert" "⦀" latexsubs)
(puthash "\\circledS" "Ⓢ" latexsubs)
(puthash "\\boxdot" "⊡" latexsubs)
(puthash "\\twoheadleftarrow" "↞" latexsubs)
(puthash "\\textpertenthousand" "‱" latexsubs)
(puthash "\\Uparrow" "⇑" latexsubs)
(puthash "\\LeftVectorBar" "⥒" latexsubs)
(puthash "\\textasciimacron" "¯" latexsubs)
(puthash "\\nolinebreak" "\u2060" latexsubs)
(puthash "\\rangle" "〉" latexsubs)
(puthash "\\libra" "♎" latexsubs)
(puthash "\\Lambda" "Λ" latexsubs)
(puthash "\\sqsupseteq" "⊒" latexsubs)
(puthash "\\odot" "⊙" latexsubs)
(puthash "\\supseteqq" "⫆" latexsubs)
(puthash "\\boxminus" "⊟" latexsubs)
(puthash "\\textasciidieresis" "¨" latexsubs)
(puthash "\\k" "̨" latexsubs)
(puthash "\\textnumero" "№" latexsubs)
(puthash "\\Pi" "Π" latexsubs)
(puthash "\\nparallel" "∦" latexsubs)
(puthash "\\Elzpalh" "̡" latexsubs)
(puthash "\\Elzsqfse" "◪" latexsubs)
(puthash "\\gtrapprox" "⪆" latexsubs)
(puthash "\\lessgtr" "≶" latexsubs)
(puthash "\\Elzrl" "ɼ" latexsubs)
(puthash "\\coloneq" "≔" latexsubs)
(puthash "\\pisces" "♓" latexsubs)
(puthash "\\Elzreapos" "‛" latexsubs)
(puthash "\\Elzsqfl" "◧" latexsubs)
(puthash "\\eqcirc" "≖" latexsubs)
(puthash "\\quarternote" "♩" latexsubs)
(puthash "\\RightVectorBar" "⥓" latexsubs)
(puthash "\\texttrademark" "™" latexsubs)
(puthash "\\upharpoonleft" "↾" latexsubs)
(puthash "\\wedgeq" "≙" latexsubs)
(puthash "\\hookrightarrow" "↪" latexsubs)
(puthash "\\supsetneq" "⊋" latexsubs)
(puthash "\\succneqq" "⪶" latexsubs)
(puthash "\\Elztrnh" "ɥ" latexsubs)
(puthash "\\precsim" "≾" latexsubs)
(puthash "\\preceq" "⪯" latexsubs)
(puthash "\\Gamma" "Γ" latexsubs)
(puthash "\\tosa" "⤩" latexsubs)
(puthash "\\notin" "∉" latexsubs)
(puthash "\\circ" "∘" latexsubs)
(puthash "\\prime" "′" latexsubs)
(puthash "\\cdot" "⋅" latexsubs)
(puthash "\\uplus" "⊎" latexsubs)
(puthash "\\rtimes" "⋊" latexsubs)
(puthash "\\Elzesh" "ʃ" latexsubs)
(puthash "\\nmid" "∤" latexsubs)
(puthash "\\DJ" "Đ" latexsubs)
(puthash "\\ElzAnd" "⩓" latexsubs)
(puthash "\\DownLeftVectorBar" "⥖" latexsubs)
(puthash "\\Supset" "⋑" latexsubs)
(puthash "\\RightUpDownVector" "⥏" latexsubs)
(puthash "\\Elzpupsil" "ʊ" latexsubs)
(puthash "\\varpi" "ϖ" latexsubs)
(puthash "\\circledast" "⊛" latexsubs)
(puthash "\\cap" "∩" latexsubs)
(puthash "\\Kappa" "Κ" latexsubs)
(puthash "\\vdash" "⊢" latexsubs)
(puthash "\\because" "∵" latexsubs)
(puthash "\\biguplus" "⨄" latexsubs)
(puthash "\\textbrokenbar" "¦" latexsubs)
(puthash "\\eqsim" "≂" latexsubs)
(puthash "\\Elzclomeg" "ɷ" latexsubs)
(puthash "\\tona" "⤧" latexsubs)
(puthash "\\setminus" "∖" latexsubs)
(puthash "\\therefore" "∴" latexsubs)
(puthash "\\leftarrowtail" "↢" latexsubs)
(puthash "\\rightanglearc" "⊾" latexsubs)
(puthash "\\measuredangle" "∡" latexsubs)
(puthash "\\LeftTeeVector" "⥚" latexsubs)
(puthash "\\longleftarrow" "⟵" latexsubs)
(puthash "\\dj" "đ" latexsubs)
(puthash "\\intprod" "⨼" latexsubs)
(puthash "\\notgreaterless" "≹" latexsubs)
(puthash "\\ElzLap" "⧊" latexsubs)
(puthash "\\gtrsim" "≳" latexsubs)
(puthash "\\adots" "⋰" latexsubs)
(puthash "\\rho" "ρ" latexsubs)
(puthash "\\leftthreetimes" "⋋" latexsubs)
(puthash "\\jupiter" "♃" latexsubs)
(puthash "\\bumpeq" "≏" latexsubs)
(puthash "\\oiint" "∯" latexsubs)
(puthash "\\Elzpgamma" "ɣ" latexsubs)
(puthash "\\dotplus" "∔" latexsubs)
(puthash "\\searrow" "↘" latexsubs)
(puthash "\\Elzlow" "˕" latexsubs)
(puthash "\\VDash" "⊫" latexsubs)
(puthash "\\boxdiag" "⧄" latexsubs)
(puthash "\\varsigma" "ς" latexsubs)
(puthash "\\sqrint" "⨖" latexsubs)
(puthash "\\nu" "ν" latexsubs)
(puthash "\\textquotedblleft" "“" latexsubs)
(puthash "\\leftrightharpoons" "⇋" latexsubs)
(puthash "\\preccurlyeq" "≼" latexsubs)
(puthash "\\ddots" "⋱" latexsubs)
(puthash "\\flat" "♭" latexsubs)
(puthash "\\otimes" "⊗" latexsubs)
(puthash "\\Elzrtll" "ɭ" latexsubs)
(puthash "\\lnapprox" "⪉" latexsubs)
(puthash "\\vartriangleleft" "⊲" latexsubs)
(puthash "\\NotSquareSuperset" "⊐̸" latexsubs)
(puthash "\\Psi" "Ψ" latexsubs)
(puthash "\\RightDownVectorBar" "⥕" latexsubs)
(puthash "\\ominus" "⊖" latexsubs)
(puthash "\\grave" "̀" latexsubs)
(puthash "\\bowtie" "⋈" latexsubs)
(puthash "\\prod" "∏" latexsubs)
(puthash "\\succcurlyeq" "≽" latexsubs)
(puthash "\\geqslant" "⩾" latexsubs)
(puthash "\\LeftDownVectorBar" "⥙" latexsubs)
(puthash "\\bigoplus" "⨁" latexsubs)
(puthash "\\nsucceq" "⪰̸" latexsubs)
(puthash "\\obslash" "⦸" latexsubs)
(puthash "\\H" "̋" latexsubs)
(puthash "\\digamma" "ϝ" latexsubs)
(puthash "\\vartriangleright" "⊳" latexsubs)
(puthash "\\nsupseteqq" "⫆̸" latexsubs)
(puthash "\\Elzglst" "ʔ" latexsubs)
(puthash "\\NestedLessLess" "⪡" latexsubs)
(puthash "\\o" "ø" latexsubs)
(puthash "\\divideontimes" "⋇" latexsubs)
(puthash "\\triangleright" "▹" latexsubs)
(puthash "\\NotNestedGreaterGreater" "⪢̸" latexsubs)
(puthash "\\diagdown" "╲" latexsubs)
(puthash "\\doteq" "≐" latexsubs)
(puthash "\\upint" "⨛" latexsubs)
(puthash "\\bigcup" "⋃" latexsubs)
(puthash "\\simeq" "≃" latexsubs)
(puthash "\\gvertneqq" "≩︀" latexsubs)
(puthash "\\rightarrowtail" "↣" latexsubs)
(puthash "\\multimap" "⊸" latexsubs)
(puthash "\\Delta" "Δ" latexsubs)
(puthash "\\Elzyogh" "ʒ" latexsubs)
(puthash "\\Rho" "Ρ" latexsubs)
(puthash "\\backprime" "‵" latexsubs)
(puthash "\\lambda" "λ" latexsubs)
(puthash "\\LeftDownTeeVector" "⥡" latexsubs)
(puthash "\\starequal" "≛" latexsubs)
(puthash "\\triangledown" "▿" latexsubs)
(puthash "\\circlearrowright" "↻" latexsubs)
(puthash "\\textquestiondown" "¿" latexsubs)
(puthash "\\blacktriangleleft" "◂" latexsubs)
(puthash "\\succnsim" "⋩" latexsubs)
(puthash "\\cong" "≅" latexsubs)
(puthash "\\varsupsetneq" "⊋︀" latexsubs)
(puthash "\\quad" " " latexsubs)
(puthash "\\bigsqcap" "⨅" latexsubs)
(puthash "\\lazysinv" "∾" latexsubs)
(puthash "\\RightTriangleBar" "⧐" latexsubs)
(puthash "\\Subset" "⋐" latexsubs)
(puthash "\\sqcap" "⊓" latexsubs)
(puthash "\\succnapprox" "⪺" latexsubs)
(puthash "\\nleq" "≰" latexsubs)
(puthash "\\Elzlpargt" "⦠" latexsubs)
(puthash "\\vee" "∨" latexsubs)
(puthash "\\approxeq" "≊" latexsubs)
(puthash "\\Elzschwa" "ə" latexsubs)
(puthash "\\RightTeeVector" "⥛" latexsubs)
(puthash "\\rightharpoonup" "⇀" latexsubs)
(puthash "\\hermitconjmatrix" "⊹" latexsubs)
(puthash "\\textordmasculine" "º" latexsubs)
(puthash "\\rightarrow" "→" latexsubs)
(puthash "\\geqq" "≧" latexsubs)
(puthash "\\Mapsfrom" "⤆" latexsubs)
(puthash "\\rmoustache" "⎱" latexsubs)
(puthash "\\u" "˘" latexsubs)
(puthash "\\intBar" "⨎" latexsubs)
(puthash "\\Epsilon" "Ε" latexsubs)
(puthash "\\RightDownTeeVector" "⥝" latexsubs)
(puthash "\\mu" "μ" latexsubs)
(puthash "\\zeta" "ζ" latexsubs)
(puthash "\\gneq" "⪈" latexsubs)
(puthash "\\curvearrowleft" "↶" latexsubs)
(puthash "\\mercury" "☿" latexsubs)
(puthash "\\le" "≤" latexsubs)
(puthash "\\ulcorner" "⌜" latexsubs)
(puthash "\\varepsilon" "ɛ" latexsubs)
(puthash "\\Elzrtld" "ɖ" latexsubs)
(puthash "\\intprodr" "⨽" latexsubs)
(puthash "\\downarrow" "↓" latexsubs)
(puthash "\\minusdot" "⨪" latexsubs)
(puthash "\\gtrdot" "⋗" latexsubs)
(puthash "\\circledR" "®" latexsubs)
(puthash "\\nVdash" "⊮" latexsubs)
(puthash "\\nsime" "≄" latexsubs)
(puthash "\\parallel" "∥" latexsubs)
(puthash "\\NotRightTriangleBar" "⧐̸" latexsubs)
(puthash "\\Digamma" "Ϝ" latexsubs)
(puthash "\\leftleftarrows" "⇇" latexsubs)
(puthash "\\nvDash" "⊭" latexsubs)
(puthash "\\Rrightarrow" "⇛" latexsubs)
(puthash "\\toea" "⤨" latexsubs)
(puthash "\\seovnearrow" "⤭" latexsubs)
(puthash "\\gneqq" "≩" latexsubs)
(puthash "\\textonehalf" "½" latexsubs)
(puthash "\\ElzRlarr" "⥂" latexsubs)
(puthash "\\Elzrtlz" "ʐ" latexsubs)
(puthash "\\oplus" "⊕" latexsubs)
(puthash "\\rceil" "⌉" latexsubs)
(puthash "\\updownarrow" "↕" latexsubs)
(puthash "\\cup" "∪" latexsubs)
(puthash "\\rdiagovsearrow" "⤰" latexsubs)
(puthash "\\varkappa" "ϰ" latexsubs)
(puthash "\\cbrt" "∛" latexsubs)
(puthash "\\trianglerighteq" "⊵" latexsubs)
(puthash "\\AA" "Å" latexsubs)
(puthash "\\exists" "∃" latexsubs)
(puthash "\\Uuparrow" "⤊" latexsubs)
(puthash "\\thickspace" " " latexsubs)
(puthash "\\endash" "–" latexsubs)
(puthash "\\oslash" "⊘" latexsubs)
(puthash "\\gnsim" "⋧" latexsubs)
(puthash "\\Chi" "Χ" latexsubs)
(puthash "\\nabla" "∇" latexsubs)
(puthash "\\models" "⊧" latexsubs)
(puthash "\\lneqq" "≨" latexsubs)
(puthash "\\Cup" "⋓" latexsubs)
(puthash "\\propto" "∝" latexsubs)
(puthash "\\rq" "’" latexsubs)
(puthash "\\mlcp" "⫛" latexsubs)
(puthash "\\leftsquigarrow" "↜" latexsubs)

(provide 'julia-mode)
