(let loop ((b (read-u8))
	   (i 0))
  (if (not (eof-object? b))
      (begin
	(if (> i 0)
	    (display ", "))
	(display "0x") (display (number->string b 16))
	(if (= 0 (modulo (+ 1 i) 16))
	    (newline))
	(loop (read-u8) (+ 1 i)))))
