echo "# This file is autogenerated using gen_mathfunctions.sh" 

if [ `uname` == "Linux" ]; then
    echo "libm = dlopen("libm.so.6")"
fi

if [ `uname` == "Darwin" ]; then
    echo "libm = dlopen(\"libm.dylib\")"
fi

for func in sin cos tan sinh cosh tanh asin acos atan log log10 exp pow erf abs finite floor ceil sqrt; do
    echo "$func(x::Float64) = ccall(dlsym(libm,\"$func\"), Float64, (Float64,), x)"
done

for func in sinf cosf tanf sinhf coshf tanhf asinf acosf atanf logf log10f expf powf erff absf finitef floorf ceilf sqrtf; do
    echo "$func(x::Float32) = ccall(dlsym(libm,\"$func\"), Float32, (Float32,), x)"
done