#!/bin/sh

test -x ./deps/root/sbin/lighttpd || { echo "Install lighttpd with \"make -C deps install-lighttpd\" " && exit 0; }

echo "Connect to http://localhost:2000/ for the web REPL."
./deps/root/sbin/lighttpd -D -f ./deps/lighttpd.conf &
./julia-release-webserver -p 2001 
