#!/bin/bash

in_glpk_h="/usr/include/glpk.h"
out_glpk_h="linprog_glpk_h.jl"

cat "$in_glpk_h" |
	grep "^#define[[:space:]]*GLP[_A-Z0-9]\+[[:space:]]*\(0x[[:digit:]A-Fa-f]\+\|[[:digit:]]\)\+" |
	sed "s@[[:space:]]*/\*.*\*/[[:space:]]*@@g" |
	sed "s/^#define[[:space:]]*\(GLP[_A-Z0-9]\+\)[[:space:]]*\(.*\)/const \1 = int32(\2)/" \
	> "$out_glpk_h"

