name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        If you have a question please search or post to our Discourse site: [https://discourse.julialang.org](https://discourse.julialang.org).
        We use the GitHub issue tracker for bug reports and feature requests only.

        If you're experiencing a problem with a particular package, open an issue on that
        package's repository instead.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the steps you took and provide any code executed to reproduce the bug, as well as any error messages that were printed.
      placeholder: |
        I executed this function:
        
        ```julia
        [...]
        ````
  
        and encountered the following error/wrong/unexpected result:
  
        [...]
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: What did you expect to happen?
      description: Please describe what you expected to happen.
      placeholder: I expected the function to return `foobar`.
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Installation Method
      description: How did you install Julia?
      placeholder: Download from julialang.org / juliaup / other (please specify)
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of julia are you running?
      placeholder: Output of `julia -e 'using InteractiveUtils; versioninfo()'`
      render: shell
    validations:
      required: true
    validations:
      required: true
