.\" To get a preview of the man page as it will actually be displayed, run
.\"
.\" > nroff -man juliac.1 | less
.\"
.\" at the terminal.
.\"

.TH JULIAC 1 2023-09-01 JULIA

.\" from the front page of https://julialang.org/
.SH NAME
juliac - Compiler driver for the julia programming language

.SH SYNOPSIS
\fBjulia\fR [OPTIONS...] \fB--\fR PROGRAMMFILE

The Julia source file \fIPROGRAMFILE\fP (optionally followed by
arguments in \fIARGS\fP) will be compiled and a binary will be
written out according to OPTIONS.

.SH DESCRIPTION
This is a placeholder for the upcoming compiler-driver for the julia
programming language. It is currently non functional. See
.BR julia (1)
for the traditional cli driver.

.SH "COMMAND-LINE OPTIONS"

.SH FILES AND ENVIRONMENT
See https://docs.julialang.org/en/v1/manual/environment-variables/

.SH BUGS
Please report any bugs using the GitHub issue tracker:
https://github.com/julialang/julia/issues?state=open

.SH AUTHORS
Contributors: https://github.com/JuliaLang/julia/graphs/contributors

.SH INTERNET RESOURCES
Website:  https://julialang.org/
.br
Documentation:  https://docs.julialang.org/
.br
Downloads:  https://julialang.org/downloads/

.SH LICENSING
Julia is an open-source project. It is made available under the MIT license.
