# These steps should only run on `sandbox.jl` machines, not `docker`-isolated ones
# since we need nestable sandboxing.  The rootfs images being used here are built from
# the `.buildkite/rootfs_images/llvm-passes.jl` file.
agents:
  queue: "julia"
  # Only run on `sandbox.jl` machines (not `docker`-isolated ones) since we need nestable sandboxing
  sandbox.jl: "true"
  os: "linux"

steps:
  - label: "asan"
    key: asan
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v2.0/llvm_passes.tar.gz
          rootfs_treehash: "0b5a80c1d0ab110a57fbdb7f4bc042a5ede310f3"
          uid: 1000
          gid: 1000
          workspaces:
            - "/cache/repos:/cache/repos"
      # `contrib/check-asan.jl` needs a `julia` binary:
      - JuliaCI/julia#v1:
          version: 1.6
    commands: |
      echo "--- Build julia-debug with ASAN"
      contrib/asan/build.sh ./tmp/test-asan -j$${JULIA_NUM_CORES} debug
      echo "--- Test that ASAN is enabled"
      contrib/asan/check.jl ./tmp/test-asan/asan/usr/bin/julia-debug
    timeout_in_minutes: 120
    # notify:
    #   - github_commit_status:
    #       context: "asan"
