FROM julia:latest

RUN apt-get update && \
    apt-get install -y && \
    apt-get build-essential && \
    apt-get libatomic1 && \ 
    apt-get python && \
    apt-get gfortran && \ 
    apt-get perl && \ 
    apt-get wget && \ 
    apt-get m4 && \ 
    apt-get cmake && \ 
    apt-get pkg-config && \
    apt-get git && \
