#!/usr/bin/env julia
# /// project
# [deps]
# Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
# ///
using Random
println("noext ok: ", Base.active_project())
# /// manifest
# julia_version = "1.13.0"
# manifest_format = "2.0"
#
# [[deps.Random]]
# uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
# version = "1.11.0"
# ///
