agents:
  queue: "julia"
  # Only run on `sandbox.jl` machines (not `docker`-isolated ones) since we need nestable sandboxing
  sandbox.jl: "true"
  os: "linux"
steps:
  - label: "analyzegc"
    key: "analyzegc"
    plugins:
      - JuliaCI/julia#v1:
          # Drop default "registries" directory, so it is not persisted from execution to execution
          persist_depot_dirs: packages,artifacts,compiled
          version: '1.6'
      - staticfloat/sandbox#v1.2:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v4.8/llvm_passes.x86_64.tar.gz
          rootfs_treehash: "c7a289a8cc544b234b1e2d7cbcce3e6815359ecd"
          workspaces:
            # Include `/cache/repos` so that our `git` version introspection works.
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- Install in-tree LLVM dependencies"
      make --output-sync -j$${JULIA_CPU_THREADS:?} -C deps install-llvm install-clang install-llvm-tools install-libuv install-utf8proc install-unwind
      echo "+++ run clangsa/analyzegc"
      make --output-sync -j$${JULIA_CPU_THREADS:?} -C test/clangsa
      make --output-sync -j$${JULIA_CPU_THREADS:?} -C src analyzegc
    timeout_in_minutes: 60
  - label: "llvmpasses"
    key: "llvmpasses"
    plugins:
      - JuliaCI/julia#v1:
          # Drop default "registries" directory, so it is not persisted from execution to execution
          persist_depot_dirs: packages,artifacts,compiled
          version: '1.6'
      - staticfloat/sandbox#v1.2:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v4.8/package_linux.x86_64.tar.gz
          rootfs_treehash: "2a058481b567f0e91b9aa3ce4ad4f09e6419355a"
          uid: 1000
          gid: 1000
          workspaces:
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- make release"
      # Enable Julia assertions: FORCE_ASSERTIONS=1
      # Enable LLVM assertions:  LLVM_ASSERTIONS=1
      export MAKE_ASSERT_FLAGS="FORCE_ASSERTIONS=1 LLVM_ASSERTIONS=1"
      make --output-sync -j$${JULIA_CPU_THREADS:?} release JULIA_PRECOMPILE=0 $${MAKE_ASSERT_FLAGS:?}
      echo "--- make src/install-analysis-deps"
      make --output-sync -j$${JULIA_CPU_THREADS:?} -C src install-analysis-deps $${MAKE_ASSERT_FLAGS:?}
      echo "+++ make test/llvmpasses"
      make --output-sync -j$${JULIA_CPU_THREADS:?} -C test/llvmpasses $${MAKE_ASSERT_FLAGS:?}
    timeout_in_minutes: 60
