agents:
  queue: "julia"
  # Only run on `sandbox.jl` machines (not `docker`-isolated ones) since we need nestable sandboxing
  sandbox.jl: "true"
  os: "linux"
steps:
  - label: "analyzegc"
    key: "analyzegc"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v3.1/llvm_passes.x86_64.tar.gz
          rootfs_treehash: "9dd715500b117a16fcfa419ea0bca0c0ca902cee"
          workspaces:
            # Include `/cache/repos` so that our `git` version introspection works.
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- Install in-tree LLVM dependencies"
      make -j$${JULIA_CPU_THREADS:?} -C deps install-llvm install-clang install-llvm-tools install-libuv install-utf8proc install-unwind
      echo "+++ run clangsa/analyzegc"
      make -j$${JULIA_CPU_THREADS:?} -C test/clangsa
      make -j$${JULIA_CPU_THREADS:?} -C src analyzegc
    timeout_in_minutes: 60
  - label: "llvmpasses"
    key: "llvmpasses"
    plugins:
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox#v1:
          rootfs_url: https://github.com/JuliaCI/rootfs-images/releases/download/v3.8/package_linux.x86_64.tar.gz
          rootfs_treehash: "84a323ae8fcc724f8ea5aca5901bbbf4bda3e519"
          uid: 1000
          gid: 1000
          workspaces:
            - "/cache/repos:/cache/repos"
    commands: |
      echo "--- make release"
      make -j$${JULIA_CPU_THREADS:?} release JULIA_PRECOMPILE=0
      echo "--- make src/install-analysis-deps"
      make -j$${JULIA_CPU_THREADS:?} -C src install-analysis-deps
      echo "+++ make test/llvmpasses"
      make -j$${JULIA_CPU_THREADS:?} -C test/llvmpasses
    timeout_in_minutes: 60
