name: Labels

permissions:
  contents: read
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  enforce-labels:
    name: Check for blocking labels
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - uses: mheap/github-action-required-labels@23e10fde7e062233401931a0eece796cd9bf3177 # v5.6.0
      with:
        mode: exactly
        count: 0
        labels: "needs docs,needs compat annotation,needs more info,needs nanosoldier run,needs news,needs pkgeval,needs tests,needs decision,DO NOT MERGE,status:DO NOT MERGE"
        add_comment: false
        message: "A PR should not be merged with `needs *` or `status:DO NOT MERGE` labels"
