name: Whitespace

permissions: {}

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  whitespace:
    name: Check whitespace
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout the JuliaLang/julia repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32 # v3.0.2
        with:
          version: '1'
      - name: Check whitespace
        run: |
          contrib/check-whitespace.jl
